// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.24.3
// source: v1/account.proto

package v1_pb

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar   string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Surname  string `protobuf:"bytes,6,opt,name=surname,proto3" json:"surname,omitempty"`
	Gender   int32  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday string `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	About    string `protobuf:"bytes,9,opt,name=about,proto3" json:"about,omitempty"`
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AccountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *AccountResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *AccountResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *AccountResponse) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

type AccountDetailUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar   string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" binding:"required,max=30"`
	Surname  string `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty" binding:"required,max=30"`
	Gender   int32  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty" binding:"oneof=0 1 2"`
	Birthday string `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty" binding:"max=10"`
	About    string `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty" binding:"max=255"`
}

func (x *AccountDetailUpdateRequest) Reset() {
	*x = AccountDetailUpdateRequest{}
	mi := &file_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDetailUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetailUpdateRequest) ProtoMessage() {}

func (x *AccountDetailUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetailUpdateRequest.ProtoReflect.Descriptor instead.
func (*AccountDetailUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountDetailUpdateRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AccountDetailUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountDetailUpdateRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *AccountDetailUpdateRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *AccountDetailUpdateRequest) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *AccountDetailUpdateRequest) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

type AccountDetailUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountDetailUpdateResponse) Reset() {
	*x = AccountDetailUpdateResponse{}
	mi := &file_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDetailUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetailUpdateResponse) ProtoMessage() {}

func (x *AccountDetailUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetailUpdateResponse.ProtoReflect.Descriptor instead.
func (*AccountDetailUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{2}
}

type AccountUsernameUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" binding:"required,min=3,max=20"`
}

func (x *AccountUsernameUpdateRequest) Reset() {
	*x = AccountUsernameUpdateRequest{}
	mi := &file_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUsernameUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUsernameUpdateRequest) ProtoMessage() {}

func (x *AccountUsernameUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUsernameUpdateRequest.ProtoReflect.Descriptor instead.
func (*AccountUsernameUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountUsernameUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AccountUsernameUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountUsernameUpdateResponse) Reset() {
	*x = AccountUsernameUpdateResponse{}
	mi := &file_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountUsernameUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUsernameUpdateResponse) ProtoMessage() {}

func (x *AccountUsernameUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUsernameUpdateResponse.ProtoReflect.Descriptor instead.
func (*AccountUsernameUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{4}
}

type AccountEmailUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty" binding:"required"`
}

func (x *AccountEmailUpdateRequest) Reset() {
	*x = AccountEmailUpdateRequest{}
	mi := &file_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEmailUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEmailUpdateRequest) ProtoMessage() {}

func (x *AccountEmailUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEmailUpdateRequest.ProtoReflect.Descriptor instead.
func (*AccountEmailUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *AccountEmailUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AccountEmailUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountEmailUpdateResponse) Reset() {
	*x = AccountEmailUpdateResponse{}
	mi := &file_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEmailUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEmailUpdateResponse) ProtoMessage() {}

func (x *AccountEmailUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEmailUpdateResponse.ProtoReflect.Descriptor instead.
func (*AccountEmailUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_proto_rawDescGZIP(), []int{6}
}

var File_v1_account_proto protoreflect.FileDescriptor

var file_v1_account_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x13, 0x74, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x74,
	0x61, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x01, 0x0a, 0x0f,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x62, 0x6f, 0x75,
	0x74, 0x22, 0xb7, 0x02, 0x0a, 0x1a, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x32, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1e, 0x9a, 0x84, 0x9e, 0x03, 0x19, 0x62, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x2c, 0x6d,
	0x61, 0x78, 0x3d, 0x33, 0x30, 0x22, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x07,
	0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1e, 0x9a,
	0x84, 0x9e, 0x03, 0x19, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x2c, 0x6d, 0x61, 0x78, 0x3d, 0x33, 0x30, 0x22, 0x52, 0x07, 0x73,
	0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x42, 0x1a, 0x9a, 0x84, 0x9e, 0x03, 0x15, 0x62, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x3d, 0x30, 0x20, 0x31, 0x20,
	0x32, 0x22, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x08, 0x62, 0x69,
	0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x15, 0x9a, 0x84,
	0x9e, 0x03, 0x10, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x6d, 0x61, 0x78, 0x3d,
	0x31, 0x30, 0x22, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x2c, 0x0a,
	0x05, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x16, 0x9a, 0x84,
	0x9e, 0x03, 0x11, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x6d, 0x61, 0x78, 0x3d,
	0x32, 0x35, 0x35, 0x22, 0x52, 0x05, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x1c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x24, 0x9a, 0x84,
	0x9e, 0x03, 0x1f, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x2c, 0x6d, 0x69, 0x6e, 0x3d, 0x33, 0x2c, 0x6d, 0x61, 0x78, 0x3d, 0x32,
	0x30, 0x22, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x1d,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a, 0x0a,
	0x19, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12,
	0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x22, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_account_proto_rawDescOnce sync.Once
	file_v1_account_proto_rawDescData = file_v1_account_proto_rawDesc
)

func file_v1_account_proto_rawDescGZIP() []byte {
	file_v1_account_proto_rawDescOnce.Do(func() {
		file_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_account_proto_rawDescData)
	})
	return file_v1_account_proto_rawDescData
}

var file_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_account_proto_goTypes = []any{
	(*AccountResponse)(nil),               // 0: v1.AccountResponse
	(*AccountDetailUpdateRequest)(nil),    // 1: v1.AccountDetailUpdateRequest
	(*AccountDetailUpdateResponse)(nil),   // 2: v1.AccountDetailUpdateResponse
	(*AccountUsernameUpdateRequest)(nil),  // 3: v1.AccountUsernameUpdateRequest
	(*AccountUsernameUpdateResponse)(nil), // 4: v1.AccountUsernameUpdateResponse
	(*AccountEmailUpdateRequest)(nil),     // 5: v1.AccountEmailUpdateRequest
	(*AccountEmailUpdateResponse)(nil),    // 6: v1.AccountEmailUpdateResponse
}
var file_v1_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_account_proto_init() }
func file_v1_account_proto_init() {
	if File_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_account_proto_goTypes,
		DependencyIndexes: file_v1_account_proto_depIdxs,
		MessageInfos:      file_v1_account_proto_msgTypes,
	}.Build()
	File_v1_account_proto = out.File
	file_v1_account_proto_rawDesc = nil
	file_v1_account_proto_goTypes = nil
	file_v1_account_proto_depIdxs = nil
}
