// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: v1/bot.proto

package v1_pb

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" binding:"required" label:"username"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotCreateRequest) Reset() {
	*x = BotCreateRequest{}
	mi := &file_v1_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCreateRequest) ProtoMessage() {}

func (x *BotCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCreateRequest.ProtoReflect.Descriptor instead.
func (*BotCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_bot_proto_rawDescGZIP(), []int{0}
}

func (x *BotCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BotCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotCreateResponse) Reset() {
	*x = BotCreateResponse{}
	mi := &file_v1_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotCreateResponse) ProtoMessage() {}

func (x *BotCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotCreateResponse.ProtoReflect.Descriptor instead.
func (*BotCreateResponse) Descriptor() ([]byte, []int) {
	return file_v1_bot_proto_rawDescGZIP(), []int{1}
}

func (x *BotCreateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type BotListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotListRequest) Reset() {
	*x = BotListRequest{}
	mi := &file_v1_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotListRequest) ProtoMessage() {}

func (x *BotListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotListRequest.ProtoReflect.Descriptor instead.
func (*BotListRequest) Descriptor() ([]byte, []int) {
	return file_v1_bot_proto_rawDescGZIP(), []int{2}
}

type BotListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Items         []*BotListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotListResponse) Reset() {
	*x = BotListResponse{}
	mi := &file_v1_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotListResponse) ProtoMessage() {}

func (x *BotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotListResponse.ProtoReflect.Descriptor instead.
func (*BotListResponse) Descriptor() ([]byte, []int) {
	return file_v1_bot_proto_rawDescGZIP(), []int{3}
}

func (x *BotListResponse) GetItems() []*BotListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type BotListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotListResponse_Item) Reset() {
	*x = BotListResponse_Item{}
	mi := &file_v1_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotListResponse_Item) ProtoMessage() {}

func (x *BotListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotListResponse_Item.ProtoReflect.Descriptor instead.
func (*BotListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_bot_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BotListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BotListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BotListResponse_Item) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_v1_bot_proto protoreflect.FileDescriptor

const file_v1_bot_proto_rawDesc = "" +
	"\n" +
	"\fv1/bot.proto\x12\x02v1\x1a\x13tagger/tagger.proto\"X\n" +
	"\x10BotCreateRequest\x12D\n" +
	"\busername\x18\x01 \x01(\tB(\x9a\x84\x9e\x03#binding:\"required\" label:\"username\"R\busername\"<\n" +
	"\x11BotCreateResponse\x12'\n" +
	"\x05token\x18\x01 \x01(\tB\x11\x9a\x84\x9e\x03\fjson:\"token\"R\x05token\"\x10\n" +
	"\x0eBotListRequest\"\xd8\x01\n" +
	"\x0fBotListResponse\x12A\n" +
	"\x05items\x18\x01 \x03(\v2\x18.v1.BotListResponse.ItemB\x11\x9a\x84\x9e\x03\fjson:\"items\"R\x05items\x1a\x81\x01\n" +
	"\x04Item\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x02id\x120\n" +
	"\busername\x18\x02 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"username\"R\busername\x12'\n" +
	"\x05token\x18\x03 \x01(\tB\x11\x9a\x84\x9e\x03\fjson:\"token\"R\x05tokenB\fZ\n" +
	"./v1;v1_pbb\x06proto3"

var (
	file_v1_bot_proto_rawDescOnce sync.Once
	file_v1_bot_proto_rawDescData []byte
)

func file_v1_bot_proto_rawDescGZIP() []byte {
	file_v1_bot_proto_rawDescOnce.Do(func() {
		file_v1_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_bot_proto_rawDesc), len(file_v1_bot_proto_rawDesc)))
	})
	return file_v1_bot_proto_rawDescData
}

var file_v1_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_bot_proto_goTypes = []any{
	(*BotCreateRequest)(nil),     // 0: v1.BotCreateRequest
	(*BotCreateResponse)(nil),    // 1: v1.BotCreateResponse
	(*BotListRequest)(nil),       // 2: v1.BotListRequest
	(*BotListResponse)(nil),      // 3: v1.BotListResponse
	(*BotListResponse_Item)(nil), // 4: v1.BotListResponse.Item
}
var file_v1_bot_proto_depIdxs = []int32{
	4, // 0: v1.BotListResponse.items:type_name -> v1.BotListResponse.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_bot_proto_init() }
func file_v1_bot_proto_init() {
	if File_v1_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_bot_proto_rawDesc), len(file_v1_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_bot_proto_goTypes,
		DependencyIndexes: file_v1_bot_proto_depIdxs,
		MessageInfos:      file_v1_bot_proto_msgTypes,
	}.Build()
	File_v1_bot_proto = out.File
	file_v1_bot_proto_goTypes = nil
	file_v1_bot_proto_depIdxs = nil
}
