// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: v1/group_chat.proto

package v1_pb

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupChatCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" binding:"required"`
	Ids           string                 `protobuf:"bytes,2,opt,name=ids,proto3" json:"ids,omitempty" binding:"required,ids"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatCreateRequest) Reset() {
	*x = GroupChatCreateRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatCreateRequest) ProtoMessage() {}

func (x *GroupChatCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatCreateRequest.ProtoReflect.Descriptor instead.
func (*GroupChatCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GroupChatCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupChatCreateRequest) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

func (x *GroupChatCreateRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GroupChatCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatCreateResponse) Reset() {
	*x = GroupChatCreateResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatCreateResponse) ProtoMessage() {}

func (x *GroupChatCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatCreateResponse.ProtoReflect.Descriptor instead.
func (*GroupChatCreateResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GroupChatCreateResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatListResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Items         []*GroupChatListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatListResponse) Reset() {
	*x = GroupChatListResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatListResponse) ProtoMessage() {}

func (x *GroupChatListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatListResponse.ProtoReflect.Descriptor instead.
func (*GroupChatListResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GroupChatListResponse) GetItems() []*GroupChatListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupChatDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required" form:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatDetailRequest) Reset() {
	*x = GroupChatDetailRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatDetailRequest) ProtoMessage() {}

func (x *GroupChatDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatDetailRequest.ProtoReflect.Descriptor instead.
func (*GroupChatDetailRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GroupChatDetailRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	IsManager     bool                   `protobuf:"varint,6,opt,name=is_manager,json=isManager,proto3" json:"is_manager"`
	IsDisturb     int32                  `protobuf:"varint,7,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb"`
	IsMute        int32                  `protobuf:"varint,8,opt,name=is_mute,json=isMute,proto3" json:"is_mute"`
	IsOvert       int32                  `protobuf:"varint,9,opt,name=is_overt,json=isOvert,proto3" json:"is_overt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatDetailResponse) Reset() {
	*x = GroupChatDetailResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatDetailResponse) ProtoMessage() {}

func (x *GroupChatDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatDetailResponse.ProtoReflect.Descriptor instead.
func (*GroupChatDetailResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GroupChatDetailResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatDetailResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupChatDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupChatDetailResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupChatDetailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupChatDetailResponse) GetIsManager() bool {
	if x != nil {
		return x.IsManager
	}
	return false
}

func (x *GroupChatDetailResponse) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

func (x *GroupChatDetailResponse) GetIsMute() int32 {
	if x != nil {
		return x.IsMute
	}
	return 0
}

func (x *GroupChatDetailResponse) GetIsOvert() int32 {
	if x != nil {
		return x.IsOvert
	}
	return 0
}

type GroupChatMemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required" form:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatMemberListRequest) Reset() {
	*x = GroupChatMemberListRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatMemberListRequest) ProtoMessage() {}

func (x *GroupChatMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatMemberListRequest.ProtoReflect.Descriptor instead.
func (*GroupChatMemberListRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GroupChatMemberListRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatMemberListResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Items         []*GroupChatMemberListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatMemberListResponse) Reset() {
	*x = GroupChatMemberListResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatMemberListResponse) ProtoMessage() {}

func (x *GroupChatMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatMemberListResponse.ProtoReflect.Descriptor instead.
func (*GroupChatMemberListResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GroupChatMemberListResponse) GetItems() []*GroupChatMemberListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupChatDismissRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatDismissRequest) Reset() {
	*x = GroupChatDismissRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatDismissRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatDismissRequest) ProtoMessage() {}

func (x *GroupChatDismissRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatDismissRequest.ProtoReflect.Descriptor instead.
func (*GroupChatDismissRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GroupChatDismissRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupDismissResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDismissResponse) Reset() {
	*x = GroupDismissResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDismissResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDismissResponse) ProtoMessage() {}

func (x *GroupDismissResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDismissResponse.ProtoReflect.Descriptor instead.
func (*GroupDismissResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{8}
}

type GroupChatInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	Ids           string                 `protobuf:"bytes,2,opt,name=ids,proto3" json:"ids,omitempty" binding:"required,ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatInviteRequest) Reset() {
	*x = GroupChatInviteRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatInviteRequest) ProtoMessage() {}

func (x *GroupChatInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatInviteRequest.ProtoReflect.Descriptor instead.
func (*GroupChatInviteRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GroupChatInviteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatInviteRequest) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

type GroupChatInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatInviteResponse) Reset() {
	*x = GroupChatInviteResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatInviteResponse) ProtoMessage() {}

func (x *GroupChatInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatInviteResponse.ProtoReflect.Descriptor instead.
func (*GroupChatInviteResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{10}
}

type GroupChatGetInviteFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" form:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatGetInviteFriendsRequest) Reset() {
	*x = GroupChatGetInviteFriendsRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatGetInviteFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatGetInviteFriendsRequest) ProtoMessage() {}

func (x *GroupChatGetInviteFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatGetInviteFriendsRequest.ProtoReflect.Descriptor instead.
func (*GroupChatGetInviteFriendsRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GroupChatGetInviteFriendsRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatLeaveRequest) Reset() {
	*x = GroupChatLeaveRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatLeaveRequest) ProtoMessage() {}

func (x *GroupChatLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatLeaveRequest.ProtoReflect.Descriptor instead.
func (*GroupChatLeaveRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GroupChatLeaveRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty" binding:"required"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty" binding:"max=255"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSettingRequest) Reset() {
	*x = GroupSettingRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSettingRequest) ProtoMessage() {}

func (x *GroupSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSettingRequest.ProtoReflect.Descriptor instead.
func (*GroupSettingRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{13}
}

func (x *GroupSettingRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupSettingRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupSettingRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupSettingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GroupChatSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatSettingResponse) Reset() {
	*x = GroupChatSettingResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatSettingResponse) ProtoMessage() {}

func (x *GroupChatSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatSettingResponse.ProtoReflect.Descriptor instead.
func (*GroupChatSettingResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{14}
}

type GroupChatRemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	MembersIds    string                 `protobuf:"bytes,2,opt,name=members_ids,json=membersIds,proto3" json:"members_ids,omitempty" binding:"required,ids"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRemoveMemberRequest) Reset() {
	*x = GroupChatRemoveMemberRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRemoveMemberRequest) ProtoMessage() {}

func (x *GroupChatRemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*GroupChatRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{15}
}

func (x *GroupChatRemoveMemberRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatRemoveMemberRequest) GetMembersIds() string {
	if x != nil {
		return x.MembersIds
	}
	return ""
}

type GroupChatRemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRemoveMemberResponse) Reset() {
	*x = GroupChatRemoveMemberResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRemoveMemberResponse) ProtoMessage() {}

func (x *GroupChatRemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*GroupChatRemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{16}
}

type GroupChatAssignAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" binding:"required"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty" binding:"required,oneof=1 2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatAssignAdminRequest) Reset() {
	*x = GroupChatAssignAdminRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatAssignAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatAssignAdminRequest) ProtoMessage() {}

func (x *GroupChatAssignAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatAssignAdminRequest.ProtoReflect.Descriptor instead.
func (*GroupChatAssignAdminRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{17}
}

func (x *GroupChatAssignAdminRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatAssignAdminRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupChatAssignAdminRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GroupChatMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty" binding:"required,oneof=1 2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatMuteRequest) Reset() {
	*x = GroupChatMuteRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatMuteRequest) ProtoMessage() {}

func (x *GroupChatMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatMuteRequest.ProtoReflect.Descriptor instead.
func (*GroupChatMuteRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{18}
}

func (x *GroupChatMuteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatMuteRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GroupChatMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatMuteResponse) Reset() {
	*x = GroupChatMuteResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatMuteResponse) ProtoMessage() {}

func (x *GroupChatMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatMuteResponse.ProtoReflect.Descriptor instead.
func (*GroupChatMuteResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{19}
}

type GroupChatOvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty" binding:"required,oneof=1 2"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatOvertRequest) Reset() {
	*x = GroupChatOvertRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatOvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatOvertRequest) ProtoMessage() {}

func (x *GroupChatOvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatOvertRequest.ProtoReflect.Descriptor instead.
func (*GroupChatOvertRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{20}
}

func (x *GroupChatOvertRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatOvertRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GroupChatOvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatOvertResponse) Reset() {
	*x = GroupChatOvertResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatOvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatOvertResponse) ProtoMessage() {}

func (x *GroupChatOvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatOvertResponse.ProtoReflect.Descriptor instead.
func (*GroupChatOvertResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{21}
}

type GroupChatRequestCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestCreateRequest) Reset() {
	*x = GroupChatRequestCreateRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestCreateRequest) ProtoMessage() {}

func (x *GroupChatRequestCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestCreateRequest.ProtoReflect.Descriptor instead.
func (*GroupChatRequestCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{22}
}

func (x *GroupChatRequestCreateRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatRequestAgreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestAgreeRequest) Reset() {
	*x = GroupChatRequestAgreeRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestAgreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestAgreeRequest) ProtoMessage() {}

func (x *GroupChatRequestAgreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestAgreeRequest.ProtoReflect.Descriptor instead.
func (*GroupChatRequestAgreeRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{23}
}

func (x *GroupChatRequestAgreeRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

type GroupChatRequestDeclineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestDeclineRequest) Reset() {
	*x = GroupChatRequestDeclineRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestDeclineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestDeclineRequest) ProtoMessage() {}

func (x *GroupChatRequestDeclineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestDeclineRequest.ProtoReflect.Descriptor instead.
func (*GroupChatRequestDeclineRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{24}
}

func (x *GroupChatRequestDeclineRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

type GroupChatRequestDeclineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestDeclineResponse) Reset() {
	*x = GroupChatRequestDeclineResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestDeclineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestDeclineResponse) ProtoMessage() {}

func (x *GroupChatRequestDeclineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestDeclineResponse.ProtoReflect.Descriptor instead.
func (*GroupChatRequestDeclineResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{25}
}

type GroupRequestListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required" form:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequestListRequest) Reset() {
	*x = GroupRequestListRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequestListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequestListRequest) ProtoMessage() {}

func (x *GroupRequestListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequestListRequest.ProtoReflect.Descriptor instead.
func (*GroupRequestListRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{26}
}

func (x *GroupRequestListRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatUnreadNumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadNum     int64                  `protobuf:"varint,1,opt,name=unread_num,json=unreadNum,proto3" json:"unread_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatUnreadNumResponse) Reset() {
	*x = GroupChatUnreadNumResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatUnreadNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatUnreadNumResponse) ProtoMessage() {}

func (x *GroupChatUnreadNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatUnreadNumResponse.ProtoReflect.Descriptor instead.
func (*GroupChatUnreadNumResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{27}
}

func (x *GroupChatUnreadNumResponse) GetUnreadNum() int64 {
	if x != nil {
		return x.UnreadNum
	}
	return 0
}

type GroupChatRequestListResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Items         []*GroupChatRequestListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestListResponse) Reset() {
	*x = GroupChatRequestListResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestListResponse) ProtoMessage() {}

func (x *GroupChatRequestListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestListResponse.ProtoReflect.Descriptor instead.
func (*GroupChatRequestListResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{28}
}

func (x *GroupChatRequestListResponse) GetItems() []*GroupChatRequestListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupChatRequestAllResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Items         []*GroupChatRequestAllResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestAllResponse) Reset() {
	*x = GroupChatRequestAllResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestAllResponse) ProtoMessage() {}

func (x *GroupChatRequestAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestAllResponse.ProtoReflect.Descriptor instead.
func (*GroupChatRequestAllResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{29}
}

func (x *GroupChatRequestAllResponse) GetItems() []*GroupChatRequestAllResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupChatAdsDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	AdsId         int32                  `protobuf:"varint,2,opt,name=ads_id,json=adsId,proto3" json:"ads_id,omitempty" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatAdsDeleteRequest) Reset() {
	*x = GroupChatAdsDeleteRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatAdsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatAdsDeleteRequest) ProtoMessage() {}

func (x *GroupChatAdsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatAdsDeleteRequest.ProtoReflect.Descriptor instead.
func (*GroupChatAdsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{30}
}

func (x *GroupChatAdsDeleteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatAdsDeleteRequest) GetAdsId() int32 {
	if x != nil {
		return x.AdsId
	}
	return 0
}

type GroupChatAdsEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required"`
	AdsId         int32                  `protobuf:"varint,2,opt,name=ads_id,json=adsId,proto3" json:"ads_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty" binding:"required"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty" binding:"required"`
	IsTop         int32                  `protobuf:"varint,5,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty" binding:"oneof=0 1"`
	IsConfirm     int32                  `protobuf:"varint,6,opt,name=is_confirm,json=isConfirm,proto3" json:"is_confirm,omitempty" binding:"oneof=0 1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatAdsEditRequest) Reset() {
	*x = GroupChatAdsEditRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatAdsEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatAdsEditRequest) ProtoMessage() {}

func (x *GroupChatAdsEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatAdsEditRequest.ProtoReflect.Descriptor instead.
func (*GroupChatAdsEditRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{31}
}

func (x *GroupChatAdsEditRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatAdsEditRequest) GetAdsId() int32 {
	if x != nil {
		return x.AdsId
	}
	return 0
}

func (x *GroupChatAdsEditRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GroupChatAdsEditRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupChatAdsEditRequest) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *GroupChatAdsEditRequest) GetIsConfirm() int32 {
	if x != nil {
		return x.IsConfirm
	}
	return 0
}

type GroupChatAdsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" binding:"required" form:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatAdsListRequest) Reset() {
	*x = GroupChatAdsListRequest{}
	mi := &file_v1_group_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatAdsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatAdsListRequest) ProtoMessage() {}

func (x *GroupChatAdsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatAdsListRequest.ProtoReflect.Descriptor instead.
func (*GroupChatAdsListRequest) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{32}
}

func (x *GroupChatAdsListRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupChatAdsListResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*GroupChatAdsListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatAdsListResponse) Reset() {
	*x = GroupChatAdsListResponse{}
	mi := &file_v1_group_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatAdsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatAdsListResponse) ProtoMessage() {}

func (x *GroupChatAdsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatAdsListResponse.ProtoReflect.Descriptor instead.
func (*GroupChatAdsListResponse) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{33}
}

func (x *GroupChatAdsListResponse) GetItems() []*GroupChatAdsListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupChatListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Leader        int32                  `protobuf:"varint,5,opt,name=leader,proto3" json:"leader"`
	IsDisturb     int32                  `protobuf:"varint,6,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb"`
	CreatorId     int32                  `protobuf:"varint,7,opt,name=creator_id,json=creatorId,proto3" json:"creator_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatListResponse_Item) Reset() {
	*x = GroupChatListResponse_Item{}
	mi := &file_v1_group_chat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatListResponse_Item) ProtoMessage() {}

func (x *GroupChatListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupChatListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GroupChatListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupChatListResponse_Item) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupChatListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupChatListResponse_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GroupChatListResponse_Item) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *GroupChatListResponse_Item) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

func (x *GroupChatListResponse_Item) GetCreatorId() int32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type GroupChatMemberListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender"`
	Leader        int32                  `protobuf:"varint,5,opt,name=leader,proto3" json:"leader"`
	IsMute        int32                  `protobuf:"varint,6,opt,name=is_mute,json=isMute,proto3" json:"is_mute"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatMemberListResponse_Item) Reset() {
	*x = GroupChatMemberListResponse_Item{}
	mi := &file_v1_group_chat_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatMemberListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatMemberListResponse_Item) ProtoMessage() {}

func (x *GroupChatMemberListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatMemberListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupChatMemberListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GroupChatMemberListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupChatMemberListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupChatMemberListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupChatMemberListResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GroupChatMemberListResponse_Item) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *GroupChatMemberListResponse_Item) GetIsMute() int32 {
	if x != nil {
		return x.IsMute
	}
	return 0
}

type GroupChatRequestListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	GroupId       int32                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestListResponse_Item) Reset() {
	*x = GroupChatRequestListResponse_Item{}
	mi := &file_v1_group_chat_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestListResponse_Item) ProtoMessage() {}

func (x *GroupChatRequestListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupChatRequestListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{28, 0}
}

func (x *GroupChatRequestListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupChatRequestListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupChatRequestListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatRequestListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupChatRequestListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupChatRequestListResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GroupChatRequestAllResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	GroupId       int32                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatRequestAllResponse_Item) Reset() {
	*x = GroupChatRequestAllResponse_Item{}
	mi := &file_v1_group_chat_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatRequestAllResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatRequestAllResponse_Item) ProtoMessage() {}

func (x *GroupChatRequestAllResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatRequestAllResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupChatRequestAllResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{29, 0}
}

func (x *GroupChatRequestAllResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupChatRequestAllResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupChatRequestAllResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupChatRequestAllResponse_Item) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupChatRequestAllResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupChatRequestAllResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupChatRequestAllResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GroupChatAdsListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
	IsTop         int32                  `protobuf:"varint,4,opt,name=is_top,json=isTop,proto3" json:"is_top"`
	IsConfirm     int32                  `protobuf:"varint,5,opt,name=is_confirm,json=isConfirm,proto3" json:"is_confirm"`
	ConfirmUsers  string                 `protobuf:"bytes,6,opt,name=confirm_users,json=confirmUsers,proto3" json:"confirm_users"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar"`
	CreatorId     int32                  `protobuf:"varint,8,opt,name=creator_id,json=creatorId,proto3" json:"creator_id"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChatAdsListResponse_Item) Reset() {
	*x = GroupChatAdsListResponse_Item{}
	mi := &file_v1_group_chat_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChatAdsListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChatAdsListResponse_Item) ProtoMessage() {}

func (x *GroupChatAdsListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_group_chat_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChatAdsListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupChatAdsListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_group_chat_proto_rawDescGZIP(), []int{33, 0}
}

func (x *GroupChatAdsListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupChatAdsListResponse_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GroupChatAdsListResponse_Item) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupChatAdsListResponse_Item) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *GroupChatAdsListResponse_Item) GetIsConfirm() int32 {
	if x != nil {
		return x.IsConfirm
	}
	return 0
}

func (x *GroupChatAdsListResponse_Item) GetConfirmUsers() string {
	if x != nil {
		return x.ConfirmUsers
	}
	return ""
}

func (x *GroupChatAdsListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupChatAdsListResponse_Item) GetCreatorId() int32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *GroupChatAdsListResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupChatAdsListResponse_Item) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_v1_group_chat_proto protoreflect.FileDescriptor

const file_v1_group_chat_proto_rawDesc = "" +
	"\n" +
	"\x13v1/group_chat.proto\x12\x02v1\x1a\x13tagger/tagger.proto\"\x8c\x01\n" +
	"\x16GroupChatCreateRequest\x12+\n" +
	"\x04name\x18\x01 \x01(\tB\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\x04name\x12-\n" +
	"\x03ids\x18\x02 \x01(\tB\x1b\x9a\x84\x9e\x03\x16binding:\"required,ids\"R\x03ids\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"J\n" +
	"\x17GroupChatCreateResponse\x12/\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"group_id\"R\agroupId\"\xc1\x03\n" +
	"\x15GroupChatListResponse\x12G\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.v1.GroupChatListResponse.ItemB\x11\x9a\x84\x9e\x03\fjson:\"items\"R\x05items\x1a\xde\x02\n" +
	"\x04Item\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x02id\x125\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"group_name\"R\tgroupName\x12*\n" +
	"\x06avatar\x18\x03 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"avatar\"R\x06avatar\x129\n" +
	"\vdescription\x18\x04 \x01(\tB\x17\x9a\x84\x9e\x03\x12json:\"description\"R\vdescription\x12*\n" +
	"\x06leader\x18\x05 \x01(\x05B\x12\x9a\x84\x9e\x03\rjson:\"leader\"R\x06leader\x125\n" +
	"\n" +
	"is_disturb\x18\x06 \x01(\x05B\x16\x9a\x84\x9e\x03\x11json:\"is_disturb\"R\tisDisturb\x125\n" +
	"\n" +
	"creator_id\x18\a \x01(\x05B\x16\x9a\x84\x9e\x03\x11json:\"creator_id\"R\tcreatorId\"\\\n" +
	"\x16GroupChatDetailRequest\x12B\n" +
	"\bgroup_id\x18\x01 \x01(\x05B'\x9a\x84\x9e\x03\"form:\"group_id\" binding:\"required\"R\agroupId\"\xec\x03\n" +
	"\x17GroupChatDetailResponse\x12/\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"group_id\"R\agroupId\x125\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"group_name\"R\tgroupName\x129\n" +
	"\vdescription\x18\x03 \x01(\tB\x17\x9a\x84\x9e\x03\x12json:\"description\"R\vdescription\x12*\n" +
	"\x06avatar\x18\x04 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"avatar\"R\x06avatar\x125\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"R\tcreatedAt\x125\n" +
	"\n" +
	"is_manager\x18\x06 \x01(\bB\x16\x9a\x84\x9e\x03\x11json:\"is_manager\"R\tisManager\x125\n" +
	"\n" +
	"is_disturb\x18\a \x01(\x05B\x16\x9a\x84\x9e\x03\x11json:\"is_disturb\"R\tisDisturb\x12,\n" +
	"\ais_mute\x18\b \x01(\x05B\x13\x9a\x84\x9e\x03\x0ejson:\"is_mute\"R\x06isMute\x12/\n" +
	"\bis_overt\x18\t \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"is_overt\"R\aisOvert\"`\n" +
	"\x1aGroupChatMemberListRequest\x12B\n" +
	"\bgroup_id\x18\x01 \x01(\x05B'\x9a\x84\x9e\x03\"form:\"group_id\" binding:\"required\"R\agroupId\"\x87\x03\n" +
	"\x1bGroupChatMemberListResponse\x12M\n" +
	"\x05items\x18\x01 \x03(\v2$.v1.GroupChatMemberListResponse.ItemB\x11\x9a\x84\x9e\x03\fjson:\"items\"R\x05items\x1a\x98\x02\n" +
	"\x04Item\x12,\n" +
	"\auser_id\x18\x01 \x01(\x05B\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"R\x06userId\x120\n" +
	"\busername\x18\x02 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"username\"R\busername\x12*\n" +
	"\x06avatar\x18\x03 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"avatar\"R\x06avatar\x12*\n" +
	"\x06gender\x18\x04 \x01(\x05B\x12\x9a\x84\x9e\x03\rjson:\"gender\"R\x06gender\x12*\n" +
	"\x06leader\x18\x05 \x01(\x05B\x12\x9a\x84\x9e\x03\rjson:\"leader\"R\x06leader\x12,\n" +
	"\ais_mute\x18\x06 \x01(\x05B\x13\x9a\x84\x9e\x03\x0ejson:\"is_mute\"R\x06isMute\"M\n" +
	"\x17GroupChatDismissRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\"\x16\n" +
	"\x14GroupDismissResponse\"{\n" +
	"\x16GroupChatInviteRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x12-\n" +
	"\x03ids\x18\x02 \x01(\tB\x1b\x9a\x84\x9e\x03\x16binding:\"required,ids\"R\x03ids\"\x19\n" +
	"\x17GroupChatInviteResponse\"S\n" +
	" GroupChatGetInviteFriendsRequest\x12/\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x14\x9a\x84\x9e\x03\x0fform:\"group_id\"R\agroupId\"K\n" +
	"\x15GroupChatLeaveRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\"\xd3\x01\n" +
	"\x13GroupSettingRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x126\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tB\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\tgroupName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x128\n" +
	"\vdescription\x18\x04 \x01(\tB\x16\x9a\x84\x9e\x03\x11binding:\"max=255\"R\vdescription\"\x1a\n" +
	"\x18GroupChatSettingResponse\"\x90\x01\n" +
	"\x1cGroupChatRemoveMemberRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x12<\n" +
	"\vmembers_ids\x18\x02 \x01(\tB\x1b\x9a\x84\x9e\x03\x16binding:\"required,ids\"R\n" +
	"membersIds\"\x1f\n" +
	"\x1dGroupChatRemoveMemberResponse\"\xba\x01\n" +
	"\x1bGroupChatAssignAdminRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x120\n" +
	"\auser_id\x18\x02 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\x06userId\x125\n" +
	"\x04mode\x18\x03 \x01(\x05B!\x9a\x84\x9e\x03\x1cbinding:\"required,oneof=1 2\"R\x04mode\"\x81\x01\n" +
	"\x14GroupChatMuteRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x125\n" +
	"\x04mode\x18\x03 \x01(\x05B!\x9a\x84\x9e\x03\x1cbinding:\"required,oneof=1 2\"R\x04mode\"\x17\n" +
	"\x15GroupChatMuteResponse\"\x82\x01\n" +
	"\x15GroupChatOvertRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x125\n" +
	"\x04mode\x18\x03 \x01(\x05B!\x9a\x84\x9e\x03\x1cbinding:\"required,oneof=1 2\"R\x04mode\"\x18\n" +
	"\x16GroupChatOvertResponse\"S\n" +
	"\x1dGroupChatRequestCreateRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\"R\n" +
	"\x1cGroupChatRequestAgreeRequest\x122\n" +
	"\bapply_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\aapplyId\"T\n" +
	"\x1eGroupChatRequestDeclineRequest\x122\n" +
	"\bapply_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\aapplyId\"!\n" +
	"\x1fGroupChatRequestDeclineResponse\"]\n" +
	"\x17GroupRequestListRequest\x12B\n" +
	"\bgroup_id\x18\x01 \x01(\x05B'\x9a\x84\x9e\x03\"form:\"group_id\" binding:\"required\"R\agroupId\";\n" +
	"\x1aGroupChatUnreadNumResponse\x12\x1d\n" +
	"\n" +
	"unread_num\x18\x01 \x01(\x03R\tunreadNum\"\x8b\x03\n" +
	"\x1cGroupChatRequestListResponse\x12N\n" +
	"\x05items\x18\x01 \x03(\v2%.v1.GroupChatRequestListResponse.ItemB\x11\x9a\x84\x9e\x03\fjson:\"items\"R\x05items\x1a\x9a\x02\n" +
	"\x04Item\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x02id\x12,\n" +
	"\auser_id\x18\x02 \x01(\x05B\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"R\x06userId\x12/\n" +
	"\bgroup_id\x18\x03 \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"group_id\"R\agroupId\x12*\n" +
	"\x06avatar\x18\x04 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"avatar\"R\x06avatar\x120\n" +
	"\busername\x18\x05 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"username\"R\busername\x125\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"R\tcreatedAt\"\xc0\x03\n" +
	"\x1bGroupChatRequestAllResponse\x12M\n" +
	"\x05items\x18\x01 \x03(\v2$.v1.GroupChatRequestAllResponse.ItemB\x11\x9a\x84\x9e\x03\fjson:\"items\"R\x05items\x1a\xd1\x02\n" +
	"\x04Item\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x02id\x12,\n" +
	"\auser_id\x18\x02 \x01(\x05B\x13\x9a\x84\x9e\x03\x0ejson:\"user_id\"R\x06userId\x12/\n" +
	"\bgroup_id\x18\x03 \x01(\x05B\x14\x9a\x84\x9e\x03\x0fjson:\"group_id\"R\agroupId\x125\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"group_name\"R\tgroupName\x12*\n" +
	"\x06avatar\x18\x05 \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"avatar\"R\x06avatar\x120\n" +
	"\busername\x18\x06 \x01(\tB\x14\x9a\x84\x9e\x03\x0fjson:\"username\"R\busername\x125\n" +
	"\n" +
	"created_at\x18\a \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"R\tcreatedAt\"\x7f\n" +
	"\x19GroupChatAdsDeleteRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x12.\n" +
	"\x06ads_id\x18\x02 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\x05adsId\"\xb0\x02\n" +
	"\x17GroupChatAdsEditRequest\x122\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\agroupId\x12\x15\n" +
	"\x06ads_id\x18\x02 \x01(\x05R\x05adsId\x12-\n" +
	"\x05title\x18\x03 \x01(\tB\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\x05title\x121\n" +
	"\acontent\x18\x04 \x01(\tB\x17\x9a\x84\x9e\x03\x12binding:\"required\"R\acontent\x12/\n" +
	"\x06is_top\x18\x05 \x01(\x05B\x18\x9a\x84\x9e\x03\x13binding:\"oneof=0 1\"R\x05isTop\x127\n" +
	"\n" +
	"is_confirm\x18\x06 \x01(\x05B\x18\x9a\x84\x9e\x03\x13binding:\"oneof=0 1\"R\tisConfirm\"]\n" +
	"\x17GroupChatAdsListRequest\x12B\n" +
	"\bgroup_id\x18\x01 \x01(\x05B'\x9a\x84\x9e\x03\"form:\"group_id\" binding:\"required\"R\agroupId\"\xda\x04\n" +
	"\x18GroupChatAdsListResponse\x12J\n" +
	"\x05items\x18\x01 \x03(\v2!.v1.GroupChatAdsListResponse.ItemB\x11\x9a\x84\x9e\x03\fjson:\"items\"R\x05items\x1a\xf1\x03\n" +
	"\x04Item\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x05B\x0e\x9a\x84\x9e\x03\tjson:\"id\"R\x02id\x12'\n" +
	"\x05title\x18\x02 \x01(\tB\x11\x9a\x84\x9e\x03\fjson:\"title\"R\x05title\x12-\n" +
	"\acontent\x18\x03 \x01(\tB\x13\x9a\x84\x9e\x03\x0ejson:\"content\"R\acontent\x12)\n" +
	"\x06is_top\x18\x04 \x01(\x05B\x12\x9a\x84\x9e\x03\rjson:\"is_top\"R\x05isTop\x125\n" +
	"\n" +
	"is_confirm\x18\x05 \x01(\x05B\x16\x9a\x84\x9e\x03\x11json:\"is_confirm\"R\tisConfirm\x12>\n" +
	"\rconfirm_users\x18\x06 \x01(\tB\x19\x9a\x84\x9e\x03\x14json:\"confirm_users\"R\fconfirmUsers\x12*\n" +
	"\x06avatar\x18\a \x01(\tB\x12\x9a\x84\x9e\x03\rjson:\"avatar\"R\x06avatar\x125\n" +
	"\n" +
	"creator_id\x18\b \x01(\x05B\x16\x9a\x84\x9e\x03\x11json:\"creator_id\"R\tcreatorId\x125\n" +
	"\n" +
	"created_at\x18\t \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"created_at\"R\tcreatedAt\x125\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tB\x16\x9a\x84\x9e\x03\x11json:\"updated_at\"R\tupdatedAtB\fZ\n" +
	"./v1;v1_pbb\x06proto3"

var (
	file_v1_group_chat_proto_rawDescOnce sync.Once
	file_v1_group_chat_proto_rawDescData []byte
)

func file_v1_group_chat_proto_rawDescGZIP() []byte {
	file_v1_group_chat_proto_rawDescOnce.Do(func() {
		file_v1_group_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_group_chat_proto_rawDesc), len(file_v1_group_chat_proto_rawDesc)))
	})
	return file_v1_group_chat_proto_rawDescData
}

var file_v1_group_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_v1_group_chat_proto_goTypes = []any{
	(*GroupChatCreateRequest)(nil),            // 0: v1.GroupChatCreateRequest
	(*GroupChatCreateResponse)(nil),           // 1: v1.GroupChatCreateResponse
	(*GroupChatListResponse)(nil),             // 2: v1.GroupChatListResponse
	(*GroupChatDetailRequest)(nil),            // 3: v1.GroupChatDetailRequest
	(*GroupChatDetailResponse)(nil),           // 4: v1.GroupChatDetailResponse
	(*GroupChatMemberListRequest)(nil),        // 5: v1.GroupChatMemberListRequest
	(*GroupChatMemberListResponse)(nil),       // 6: v1.GroupChatMemberListResponse
	(*GroupChatDismissRequest)(nil),           // 7: v1.GroupChatDismissRequest
	(*GroupDismissResponse)(nil),              // 8: v1.GroupDismissResponse
	(*GroupChatInviteRequest)(nil),            // 9: v1.GroupChatInviteRequest
	(*GroupChatInviteResponse)(nil),           // 10: v1.GroupChatInviteResponse
	(*GroupChatGetInviteFriendsRequest)(nil),  // 11: v1.GroupChatGetInviteFriendsRequest
	(*GroupChatLeaveRequest)(nil),             // 12: v1.GroupChatLeaveRequest
	(*GroupSettingRequest)(nil),               // 13: v1.GroupSettingRequest
	(*GroupChatSettingResponse)(nil),          // 14: v1.GroupChatSettingResponse
	(*GroupChatRemoveMemberRequest)(nil),      // 15: v1.GroupChatRemoveMemberRequest
	(*GroupChatRemoveMemberResponse)(nil),     // 16: v1.GroupChatRemoveMemberResponse
	(*GroupChatAssignAdminRequest)(nil),       // 17: v1.GroupChatAssignAdminRequest
	(*GroupChatMuteRequest)(nil),              // 18: v1.GroupChatMuteRequest
	(*GroupChatMuteResponse)(nil),             // 19: v1.GroupChatMuteResponse
	(*GroupChatOvertRequest)(nil),             // 20: v1.GroupChatOvertRequest
	(*GroupChatOvertResponse)(nil),            // 21: v1.GroupChatOvertResponse
	(*GroupChatRequestCreateRequest)(nil),     // 22: v1.GroupChatRequestCreateRequest
	(*GroupChatRequestAgreeRequest)(nil),      // 23: v1.GroupChatRequestAgreeRequest
	(*GroupChatRequestDeclineRequest)(nil),    // 24: v1.GroupChatRequestDeclineRequest
	(*GroupChatRequestDeclineResponse)(nil),   // 25: v1.GroupChatRequestDeclineResponse
	(*GroupRequestListRequest)(nil),           // 26: v1.GroupRequestListRequest
	(*GroupChatUnreadNumResponse)(nil),        // 27: v1.GroupChatUnreadNumResponse
	(*GroupChatRequestListResponse)(nil),      // 28: v1.GroupChatRequestListResponse
	(*GroupChatRequestAllResponse)(nil),       // 29: v1.GroupChatRequestAllResponse
	(*GroupChatAdsDeleteRequest)(nil),         // 30: v1.GroupChatAdsDeleteRequest
	(*GroupChatAdsEditRequest)(nil),           // 31: v1.GroupChatAdsEditRequest
	(*GroupChatAdsListRequest)(nil),           // 32: v1.GroupChatAdsListRequest
	(*GroupChatAdsListResponse)(nil),          // 33: v1.GroupChatAdsListResponse
	(*GroupChatListResponse_Item)(nil),        // 34: v1.GroupChatListResponse.Item
	(*GroupChatMemberListResponse_Item)(nil),  // 35: v1.GroupChatMemberListResponse.Item
	(*GroupChatRequestListResponse_Item)(nil), // 36: v1.GroupChatRequestListResponse.Item
	(*GroupChatRequestAllResponse_Item)(nil),  // 37: v1.GroupChatRequestAllResponse.Item
	(*GroupChatAdsListResponse_Item)(nil),     // 38: v1.GroupChatAdsListResponse.Item
}
var file_v1_group_chat_proto_depIdxs = []int32{
	34, // 0: v1.GroupChatListResponse.items:type_name -> v1.GroupChatListResponse.Item
	35, // 1: v1.GroupChatMemberListResponse.items:type_name -> v1.GroupChatMemberListResponse.Item
	36, // 2: v1.GroupChatRequestListResponse.items:type_name -> v1.GroupChatRequestListResponse.Item
	37, // 3: v1.GroupChatRequestAllResponse.items:type_name -> v1.GroupChatRequestAllResponse.Item
	38, // 4: v1.GroupChatAdsListResponse.items:type_name -> v1.GroupChatAdsListResponse.Item
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_group_chat_proto_init() }
func file_v1_group_chat_proto_init() {
	if File_v1_group_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_group_chat_proto_rawDesc), len(file_v1_group_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_group_chat_proto_goTypes,
		DependencyIndexes: file_v1_group_chat_proto_depIdxs,
		MessageInfos:      file_v1_group_chat_proto_msgTypes,
	}.Build()
	File_v1_group_chat_proto = out.File
	file_v1_group_chat_proto_goTypes = nil
	file_v1_group_chat_proto_depIdxs = nil
}
