services:
  nginx:
    container_name: nginx
    image: nginx:1.27.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-voo
    depends_on:
      - web
      - http-server
      - ws-server

  web:
    container_name: web
    build:
      context: ./web/web-client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .env:/usr/src/voo-su/.env
    networks:
      - network-voo
    depends_on:
      - http-server
      - ws-server

  http-server:
    container_name: http-server
    build:
      context: ./
      dockerfile: deployments/docker/Dockerfile
    command: /usr/bin/voo-su http
    restart: always
    networks:
      - network-voo
    depends_on:
      - postgres
      - redis
      - clickhouse
      - minio
      - nats

  ws-server:
    container_name: ws-server
    build:
      context: ./
      dockerfile: deployments/docker/Dockerfile
    command: /usr/bin/voo-su ws
    restart: always
    networks:
      - network-voo
    depends_on:
      - postgres
      - redis
      - clickhouse
      - minio
      - nats

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voo_su
    networks:
      - network-voo

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    networks:
      - network-voo

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:25.2.2
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=voo_su
    networks:
      - network-voo

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --address ":9001" --console-address ":9002" /data
    networks:
      - network-voo

  nats:
    container_name: nats
    image: nats:2.11.0
    networks:
      - network-voo

networks:
  network-voo:
    driver: bridge
