version: '3.9'
services:
  app:
    container_name: voo_su
    build:
      context: .
      dockerfile: deployments/Dockerfile
    restart: always
    ports:
      - '2222:22'
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voo_su
    networks:
      - app-network
    volumes:
      - ./runtime/db/postgres/:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
