services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: deployments/Dockerfile
    restart: always
    volumes:
      - ${PWD}:/opt/voo-su
    ports:
      - '2222:22'
      - '8000:8000'
      - '8001:8001'
    networks:
      - network-voo
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voo_su
    ports:
      - '5432:5432'
    networks:
      - network-voo
    volumes:
      - ./runtime/db/postgres/:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '63790:6379'
    networks:
      - network-voo

networks:
  network-voo:
    driver: bridge
