services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voo_su
    volumes:
      - ./storage/db/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.8
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=voo_su
    volumes:
      - ./storage/db/clickhouse/:/var/lib/clickhouse:cached
    ports:
      - 9000:9000
      - 8123:8123

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z.fips
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --address ":9001" --console-address ":9002" /data
    volumes:
      - ./storage/db/minio/:/data
    ports:
      - 9001:9001
      - 9002:9002

  nats:
    image: nats:2.10.24
    ports:
      - 4222:4222
