services:
  postgres:
    container_name: postgres_dev
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voo_su
    ports:
      - 5432:5432

  redis:
    container_name: redis_dev
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379

  clickhouse:
    container_name: clickhouse_dev
    image: clickhouse/clickhouse-server:25.2.2
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=voo_su
    ports:
      - 9000:9000
      - 8123:8123

  minio:
    container_name: minio_dev
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --address ":9001" --console-address ":9002" /data
    ports:
      - 9001:9001
      - 9002:9002

  nats:
    container_name: nats_dev
    image: nats:2.11.0
    ports:
      - 4222:4222
