// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: v1/contact.proto

package api_v1

import (
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactListRequest) Reset() {
	*x = ContactListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListRequest) ProtoMessage() {}

func (x *ContactListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListRequest.ProtoReflect.Descriptor instead.
func (*ContactListRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{0}
}

type ContactListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ContactListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ContactListResponse) Reset() {
	*x = ContactListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse) ProtoMessage() {}

func (x *ContactListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse.ProtoReflect.Descriptor instead.
func (*ContactListResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{1}
}

func (x *ContactListResponse) GetItems() []*ContactListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId int32 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty" binding:"required"`
}

func (x *ContactDeleteRequest) Reset() {
	*x = ContactDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDeleteRequest) ProtoMessage() {}

func (x *ContactDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContactDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{2}
}

func (x *ContactDeleteRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type ContactDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactDeleteResponse) Reset() {
	*x = ContactDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDeleteResponse) ProtoMessage() {}

func (x *ContactDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDeleteResponse.ProtoReflect.Descriptor instead.
func (*ContactDeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{3}
}

type ContactDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" form:"user_id" binding:"required"`
}

func (x *ContactDetailRequest) Reset() {
	*x = ContactDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetailRequest) ProtoMessage() {}

func (x *ContactDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetailRequest.ProtoReflect.Descriptor instead.
func (*ContactDetailRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{4}
}

func (x *ContactDetailRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ContactDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username     string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar       string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name         string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Surname      string `protobuf:"bytes,5,opt,name=surname,proto3" json:"surname,omitempty"`
	Gender       int32  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	About        string `protobuf:"bytes,7,opt,name=about,proto3" json:"about,omitempty"`
	FriendStatus int32  `protobuf:"varint,8,opt,name=friend_status,json=friendStatus,proto3" json:"friend_status,omitempty"`
	GroupId      int32  `protobuf:"varint,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	IsBot        int32  `protobuf:"varint,10,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
}

func (x *ContactDetailResponse) Reset() {
	*x = ContactDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetailResponse) ProtoMessage() {}

func (x *ContactDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetailResponse.ProtoReflect.Descriptor instead.
func (*ContactDetailResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{5}
}

func (x *ContactDetailResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactDetailResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactDetailResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactDetailResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *ContactDetailResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactDetailResponse) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *ContactDetailResponse) GetFriendStatus() int32 {
	if x != nil {
		return x.FriendStatus
	}
	return 0
}

func (x *ContactDetailResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ContactDetailResponse) GetIsBot() int32 {
	if x != nil {
		return x.IsBot
	}
	return 0
}

type ContactChangeGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" form:"user_id" binding:"required"`
	GroupId int32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" form:"group_id"`
}

func (x *ContactChangeGroupRequest) Reset() {
	*x = ContactChangeGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactChangeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactChangeGroupRequest) ProtoMessage() {}

func (x *ContactChangeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactChangeGroupRequest.ProtoReflect.Descriptor instead.
func (*ContactChangeGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{6}
}

func (x *ContactChangeGroupRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactChangeGroupRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ContactChangeGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactChangeGroupResponse) Reset() {
	*x = ContactChangeGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactChangeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactChangeGroupResponse) ProtoMessage() {}

func (x *ContactChangeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactChangeGroupResponse.ProtoReflect.Descriptor instead.
func (*ContactChangeGroupResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{7}
}

type ContactRequestCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId int32 `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty" binding:"required"`
}

func (x *ContactRequestCreateRequest) Reset() {
	*x = ContactRequestCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestCreateRequest) ProtoMessage() {}

func (x *ContactRequestCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestCreateRequest.ProtoReflect.Descriptor instead.
func (*ContactRequestCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{8}
}

func (x *ContactRequestCreateRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type ContactRequestCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactRequestCreateResponse) Reset() {
	*x = ContactRequestCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestCreateResponse) ProtoMessage() {}

func (x *ContactRequestCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestCreateResponse.ProtoReflect.Descriptor instead.
func (*ContactRequestCreateResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{9}
}

type ContactRequestAcceptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyId int32 `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty" binding:"required"`
}

func (x *ContactRequestAcceptRequest) Reset() {
	*x = ContactRequestAcceptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestAcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestAcceptRequest) ProtoMessage() {}

func (x *ContactRequestAcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestAcceptRequest.ProtoReflect.Descriptor instead.
func (*ContactRequestAcceptRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{10}
}

func (x *ContactRequestAcceptRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

type ContactRequestAcceptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactRequestAcceptResponse) Reset() {
	*x = ContactRequestAcceptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestAcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestAcceptResponse) ProtoMessage() {}

func (x *ContactRequestAcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestAcceptResponse.ProtoReflect.Descriptor instead.
func (*ContactRequestAcceptResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{11}
}

type ContactRequestDeclineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplyId int32 `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty" binding:"required"`
}

func (x *ContactRequestDeclineRequest) Reset() {
	*x = ContactRequestDeclineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestDeclineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestDeclineRequest) ProtoMessage() {}

func (x *ContactRequestDeclineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestDeclineRequest.ProtoReflect.Descriptor instead.
func (*ContactRequestDeclineRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{12}
}

func (x *ContactRequestDeclineRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

type ContactRequestDeclineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactRequestDeclineResponse) Reset() {
	*x = ContactRequestDeclineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestDeclineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestDeclineResponse) ProtoMessage() {}

func (x *ContactRequestDeclineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestDeclineResponse.ProtoReflect.Descriptor instead.
func (*ContactRequestDeclineResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{13}
}

type ContactRequestListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ContactRequestListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ContactRequestListResponse) Reset() {
	*x = ContactRequestListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestListResponse) ProtoMessage() {}

func (x *ContactRequestListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestListResponse.ProtoReflect.Descriptor instead.
func (*ContactRequestListResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{14}
}

func (x *ContactRequestListResponse) GetItems() []*ContactRequestListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactFolderCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" binding:"required"`
	Sort int32  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty" binding:"required"`
}

func (x *ContactFolderCreateRequest) Reset() {
	*x = ContactFolderCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderCreateRequest) ProtoMessage() {}

func (x *ContactFolderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderCreateRequest.ProtoReflect.Descriptor instead.
func (*ContactFolderCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{15}
}

func (x *ContactFolderCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactFolderCreateRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ContactFolderCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ContactFolderCreateResponse) Reset() {
	*x = ContactFolderCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderCreateResponse) ProtoMessage() {}

func (x *ContactFolderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderCreateResponse.ProtoReflect.Descriptor instead.
func (*ContactFolderCreateResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{16}
}

func (x *ContactFolderCreateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ContactFolderUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" binding:"required"`
	Sort int32  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty" binding:"required"`
}

func (x *ContactFolderUpdateRequest) Reset() {
	*x = ContactFolderUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderUpdateRequest) ProtoMessage() {}

func (x *ContactFolderUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderUpdateRequest.ProtoReflect.Descriptor instead.
func (*ContactFolderUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{17}
}

func (x *ContactFolderUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactFolderUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactFolderUpdateRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ContactFolderUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ContactFolderUpdateResponse) Reset() {
	*x = ContactFolderUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderUpdateResponse) ProtoMessage() {}

func (x *ContactFolderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderUpdateResponse.ProtoReflect.Descriptor instead.
func (*ContactFolderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{18}
}

func (x *ContactFolderUpdateResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ContactFolderDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
}

func (x *ContactFolderDeleteRequest) Reset() {
	*x = ContactFolderDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderDeleteRequest) ProtoMessage() {}

func (x *ContactFolderDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContactFolderDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{19}
}

func (x *ContactFolderDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ContactFolderDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ContactFolderDeleteResponse) Reset() {
	*x = ContactFolderDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderDeleteResponse) ProtoMessage() {}

func (x *ContactFolderDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderDeleteResponse.ProtoReflect.Descriptor instead.
func (*ContactFolderDeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{20}
}

func (x *ContactFolderDeleteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ContactFolderSortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ContactFolderSortRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" binding:"required"`
}

func (x *ContactFolderSortRequest) Reset() {
	*x = ContactFolderSortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderSortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderSortRequest) ProtoMessage() {}

func (x *ContactFolderSortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderSortRequest.ProtoReflect.Descriptor instead.
func (*ContactFolderSortRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{21}
}

func (x *ContactFolderSortRequest) GetItems() []*ContactFolderSortRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactFolderSortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactFolderSortResponse) Reset() {
	*x = ContactFolderSortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderSortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderSortResponse) ProtoMessage() {}

func (x *ContactFolderSortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderSortResponse.ProtoReflect.Descriptor instead.
func (*ContactFolderSortResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{22}
}

type ContactFolderListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactFolderListRequest) Reset() {
	*x = ContactFolderListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderListRequest) ProtoMessage() {}

func (x *ContactFolderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderListRequest.ProtoReflect.Descriptor instead.
func (*ContactFolderListRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{23}
}

type ContactFolderListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ContactFolderListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ContactFolderListResponse) Reset() {
	*x = ContactFolderListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderListResponse) ProtoMessage() {}

func (x *ContactFolderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderListResponse.ProtoReflect.Descriptor instead.
func (*ContactFolderListResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{24}
}

func (x *ContactFolderListResponse) GetItems() []*ContactFolderListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactFolderSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ContactFolderSaveRequest_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" binding:"required"`
}

func (x *ContactFolderSaveRequest) Reset() {
	*x = ContactFolderSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderSaveRequest) ProtoMessage() {}

func (x *ContactFolderSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderSaveRequest.ProtoReflect.Descriptor instead.
func (*ContactFolderSaveRequest) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{25}
}

func (x *ContactFolderSaveRequest) GetItems() []*ContactFolderSaveRequest_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ContactFolderSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContactFolderSaveResponse) Reset() {
	*x = ContactFolderSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderSaveResponse) ProtoMessage() {}

func (x *ContactFolderSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderSaveResponse.ProtoReflect.Descriptor instead.
func (*ContactFolderSaveResponse) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{26}
}

type ContactListResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Surname  string `protobuf:"bytes,5,opt,name=surname,proto3" json:"surname,omitempty"`
	Gender   int32  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	About    string `protobuf:"bytes,7,opt,name=about,proto3" json:"about,omitempty"`
	IsOnline int32  `protobuf:"varint,8,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	GroupId  int32  `protobuf:"varint,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // string remark = 10;
}

func (x *ContactListResponse_Item) Reset() {
	*x = ContactListResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse_Item) ProtoMessage() {}

func (x *ContactListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ContactListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactListResponse_Item) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *ContactListResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactListResponse_Item) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *ContactListResponse_Item) GetIsOnline() int32 {
	if x != nil {
		return x.IsOnline
	}
	return 0
}

func (x *ContactListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ContactRequestListResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId int32  `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name     string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Surname  string `protobuf:"bytes,7,opt,name=surname,proto3" json:"surname,omitempty"`
}

func (x *ContactRequestListResponse_Item) Reset() {
	*x = ContactRequestListResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactRequestListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRequestListResponse_Item) ProtoMessage() {}

func (x *ContactRequestListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRequestListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactRequestListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{14, 0}
}

func (x *ContactRequestListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactRequestListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactRequestListResponse_Item) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ContactRequestListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactRequestListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactRequestListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactRequestListResponse_Item) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type ContactFolderSortRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
	Sort int32 `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty" binding:"required"`
}

func (x *ContactFolderSortRequest_Item) Reset() {
	*x = ContactFolderSortRequest_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderSortRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderSortRequest_Item) ProtoMessage() {}

func (x *ContactFolderSortRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderSortRequest_Item.ProtoReflect.Descriptor instead.
func (*ContactFolderSortRequest_Item) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{21, 0}
}

func (x *ContactFolderSortRequest_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactFolderSortRequest_Item) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ContactFolderListResponse_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count int32  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Sort  int32  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *ContactFolderListResponse_Item) Reset() {
	*x = ContactFolderListResponse_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderListResponse_Item) ProtoMessage() {}

func (x *ContactFolderListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactFolderListResponse_Item) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{24, 0}
}

func (x *ContactFolderListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactFolderListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactFolderListResponse_Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContactFolderListResponse_Item) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type ContactFolderSaveRequest_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" binding:"required"`
	Sort int32  `protobuf:"varint,2,opt,name=sort,proto3" json:"sort,omitempty" binding:"required"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" binding:"required"`
}

func (x *ContactFolderSaveRequest_Item) Reset() {
	*x = ContactFolderSaveRequest_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_contact_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactFolderSaveRequest_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactFolderSaveRequest_Item) ProtoMessage() {}

func (x *ContactFolderSaveRequest_Item) ProtoReflect() protoreflect.Message {
	mi := &file_v1_contact_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactFolderSaveRequest_Item.ProtoReflect.Descriptor instead.
func (*ContactFolderSaveRequest_Item) Descriptor() ([]byte, []int) {
	return file_v1_contact_proto_rawDescGZIP(), []int{25, 0}
}

func (x *ContactFolderSaveRequest_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContactFolderSaveRequest_Item) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ContactFolderSaveRequest_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1_contact_proto protoreflect.FileDescriptor

var file_v1_contact_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x2f, 0x74, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x74, 0x61, 0x67, 0x67, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xaa, 0x02,
	0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xde, 0x01, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x62, 0x6f, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x62, 0x6f,
	0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x14, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x08,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x57, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x26, 0x9a, 0x84, 0x9e, 0x03,
	0x21, 0x66, 0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x20,
	0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x22, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8e, 0x02, 0x0a, 0x15, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x62, 0x6f, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x42, 0x6f, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x19,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x26, 0x9a, 0x84, 0x9e, 0x03,
	0x21, 0x66, 0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x20,
	0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x22, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x14, 0x9a, 0x84,
	0x9e, 0x03, 0x0f, 0x66, 0x6f, 0x72, 0x6d, 0x3a, 0x22, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x22, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x1b, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e,
	0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x22, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x22, 0x1e,
	0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x51,
	0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x08, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x49,
	0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x52, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x32, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x6c, 0x79, 0x49, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x88, 0x02, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x1a, 0xae, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x76, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0x9a,
	0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03,
	0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x22, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x2d, 0x0a, 0x1b, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17,
	0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e,
	0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x22, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x2d, 0x0a, 0x1b, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x1a, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2d, 0x0a, 0x1b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0xca, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x53, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x17,
	0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x5c,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x27, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2b, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a,
	0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x1b, 0x0a, 0x19,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x54, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x22, 0xf8, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x50, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x89, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x27, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x42, 0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x3a, 0x22, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x17, 0x9a, 0x84, 0x9e, 0x03, 0x12, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x3a, 0x22, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1b,
	0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v1_contact_proto_rawDescOnce sync.Once
	file_v1_contact_proto_rawDescData = file_v1_contact_proto_rawDesc
)

func file_v1_contact_proto_rawDescGZIP() []byte {
	file_v1_contact_proto_rawDescOnce.Do(func() {
		file_v1_contact_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_contact_proto_rawDescData)
	})
	return file_v1_contact_proto_rawDescData
}

var file_v1_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_v1_contact_proto_goTypes = []interface{}{
	(*ContactListRequest)(nil),              // 0: v1.ContactListRequest
	(*ContactListResponse)(nil),             // 1: v1.ContactListResponse
	(*ContactDeleteRequest)(nil),            // 2: v1.ContactDeleteRequest
	(*ContactDeleteResponse)(nil),           // 3: v1.ContactDeleteResponse
	(*ContactDetailRequest)(nil),            // 4: v1.ContactDetailRequest
	(*ContactDetailResponse)(nil),           // 5: v1.ContactDetailResponse
	(*ContactChangeGroupRequest)(nil),       // 6: v1.ContactChangeGroupRequest
	(*ContactChangeGroupResponse)(nil),      // 7: v1.ContactChangeGroupResponse
	(*ContactRequestCreateRequest)(nil),     // 8: v1.ContactRequestCreateRequest
	(*ContactRequestCreateResponse)(nil),    // 9: v1.ContactRequestCreateResponse
	(*ContactRequestAcceptRequest)(nil),     // 10: v1.ContactRequestAcceptRequest
	(*ContactRequestAcceptResponse)(nil),    // 11: v1.ContactRequestAcceptResponse
	(*ContactRequestDeclineRequest)(nil),    // 12: v1.ContactRequestDeclineRequest
	(*ContactRequestDeclineResponse)(nil),   // 13: v1.ContactRequestDeclineResponse
	(*ContactRequestListResponse)(nil),      // 14: v1.ContactRequestListResponse
	(*ContactFolderCreateRequest)(nil),      // 15: v1.ContactFolderCreateRequest
	(*ContactFolderCreateResponse)(nil),     // 16: v1.ContactFolderCreateResponse
	(*ContactFolderUpdateRequest)(nil),      // 17: v1.ContactFolderUpdateRequest
	(*ContactFolderUpdateResponse)(nil),     // 18: v1.ContactFolderUpdateResponse
	(*ContactFolderDeleteRequest)(nil),      // 19: v1.ContactFolderDeleteRequest
	(*ContactFolderDeleteResponse)(nil),     // 20: v1.ContactFolderDeleteResponse
	(*ContactFolderSortRequest)(nil),        // 21: v1.ContactFolderSortRequest
	(*ContactFolderSortResponse)(nil),       // 22: v1.ContactFolderSortResponse
	(*ContactFolderListRequest)(nil),        // 23: v1.ContactFolderListRequest
	(*ContactFolderListResponse)(nil),       // 24: v1.ContactFolderListResponse
	(*ContactFolderSaveRequest)(nil),        // 25: v1.ContactFolderSaveRequest
	(*ContactFolderSaveResponse)(nil),       // 26: v1.ContactFolderSaveResponse
	(*ContactListResponse_Item)(nil),        // 27: v1.ContactListResponse.Item
	(*ContactRequestListResponse_Item)(nil), // 28: v1.ContactRequestListResponse.Item
	(*ContactFolderSortRequest_Item)(nil),   // 29: v1.ContactFolderSortRequest.Item
	(*ContactFolderListResponse_Item)(nil),  // 30: v1.ContactFolderListResponse.Item
	(*ContactFolderSaveRequest_Item)(nil),   // 31: v1.ContactFolderSaveRequest.Item
}
var file_v1_contact_proto_depIdxs = []int32{
	27, // 0: v1.ContactListResponse.items:type_name -> v1.ContactListResponse.Item
	28, // 1: v1.ContactRequestListResponse.items:type_name -> v1.ContactRequestListResponse.Item
	29, // 2: v1.ContactFolderSortRequest.items:type_name -> v1.ContactFolderSortRequest.Item
	30, // 3: v1.ContactFolderListResponse.items:type_name -> v1.ContactFolderListResponse.Item
	31, // 4: v1.ContactFolderSaveRequest.items:type_name -> v1.ContactFolderSaveRequest.Item
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_v1_contact_proto_init() }
func file_v1_contact_proto_init() {
	if File_v1_contact_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_contact_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactChangeGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactChangeGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestAcceptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestAcceptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestDeclineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestDeclineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderSortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderSortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactListResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactRequestListResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderSortRequest_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderListResponse_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_contact_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactFolderSaveRequest_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_contact_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_contact_proto_goTypes,
		DependencyIndexes: file_v1_contact_proto_depIdxs,
		MessageInfos:      file_v1_contact_proto_msgTypes,
	}.Build()
	File_v1_contact_proto = out.File
	file_v1_contact_proto_rawDesc = nil
	file_v1_contact_proto_goTypes = nil
	file_v1_contact_proto_depIdxs = nil
}
