// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/project_task.proto

package api_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProjectTaskCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskCreateRequestMultiError, or nil if none found.
func (m *ProjectTaskCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for TypeId

	// no validation rules for Title

	// no validation rules for Description

	if len(errors) > 0 {
		return ProjectTaskCreateRequestMultiError(errors)
	}

	return nil
}

// ProjectTaskCreateRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type ProjectTaskCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskCreateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskCreateRequestMultiError) AllErrors() []error { return m }

// ProjectTaskCreateRequestValidationError is the validation error returned by
// ProjectTaskCreateRequest.Validate if the designated constraints aren't met.
type ProjectTaskCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskCreateRequestValidationError) ErrorName() string {
	return "ProjectTaskCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskCreateRequestValidationError{}

// Validate checks the field values on ProjectTaskCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskCreateResponseMultiError, or nil if none found.
func (m *ProjectTaskCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return ProjectTaskCreateResponseMultiError(errors)
	}

	return nil
}

// ProjectTaskCreateResponseMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskCreateResponse.ValidateAll() if the
// designated constraints aren't met.
type ProjectTaskCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskCreateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskCreateResponseMultiError) AllErrors() []error { return m }

// ProjectTaskCreateResponseValidationError is the validation error returned by
// ProjectTaskCreateResponse.Validate if the designated constraints aren't met.
type ProjectTaskCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskCreateResponseValidationError) ErrorName() string {
	return "ProjectTaskCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskCreateResponseValidationError{}

// Validate checks the field values on ProjectTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskRequestMultiError, or nil if none found.
func (m *ProjectTaskRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ProjectTaskRequestMultiError(errors)
	}

	return nil
}

// ProjectTaskRequestMultiError is an error wrapping multiple validation errors
// returned by ProjectTaskRequest.ValidateAll() if the designated constraints
// aren't met.
type ProjectTaskRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskRequestMultiError) AllErrors() []error { return m }

// ProjectTaskRequestValidationError is the validation error returned by
// ProjectTaskRequest.Validate if the designated constraints aren't met.
type ProjectTaskRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskRequestValidationError) ErrorName() string {
	return "ProjectTaskRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskRequestValidationError{}

// Validate checks the field values on ProjectTaskResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskResponseMultiError, or nil if none found.
func (m *ProjectTaskResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCategories() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectTaskResponseValidationError{
						field:  fmt.Sprintf("Categories[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectTaskResponseValidationError{
						field:  fmt.Sprintf("Categories[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectTaskResponseValidationError{
					field:  fmt.Sprintf("Categories[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProjectTaskResponseMultiError(errors)
	}

	return nil
}

// ProjectTaskResponseMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskResponse.ValidateAll() if the designated
// constraints aren't met.
type ProjectTaskResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskResponseMultiError) AllErrors() []error { return m }

// ProjectTaskResponseValidationError is the validation error returned by
// ProjectTaskResponse.Validate if the designated constraints aren't met.
type ProjectTaskResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskResponseValidationError) ErrorName() string {
	return "ProjectTaskResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskResponseValidationError{}

// Validate checks the field values on ProjectTaskMoveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskMoveRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskMoveRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskMoveRequestMultiError, or nil if none found.
func (m *ProjectTaskMoveRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskMoveRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for TaskId

	// no validation rules for FromId

	// no validation rules for ToId

	if len(errors) > 0 {
		return ProjectTaskMoveRequestMultiError(errors)
	}

	return nil
}

// ProjectTaskMoveRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskMoveRequest.ValidateAll() if the designated
// constraints aren't met.
type ProjectTaskMoveRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskMoveRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskMoveRequestMultiError) AllErrors() []error { return m }

// ProjectTaskMoveRequestValidationError is the validation error returned by
// ProjectTaskMoveRequest.Validate if the designated constraints aren't met.
type ProjectTaskMoveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskMoveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskMoveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskMoveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskMoveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskMoveRequestValidationError) ErrorName() string {
	return "ProjectTaskMoveRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskMoveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskMoveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskMoveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskMoveRequestValidationError{}

// Validate checks the field values on ProjectTaskMoveResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskMoveResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskMoveResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskMoveResponseMultiError, or nil if none found.
func (m *ProjectTaskMoveResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskMoveResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ProjectTaskMoveResponseMultiError(errors)
	}

	return nil
}

// ProjectTaskMoveResponseMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskMoveResponse.ValidateAll() if the designated
// constraints aren't met.
type ProjectTaskMoveResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskMoveResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskMoveResponseMultiError) AllErrors() []error { return m }

// ProjectTaskMoveResponseValidationError is the validation error returned by
// ProjectTaskMoveResponse.Validate if the designated constraints aren't met.
type ProjectTaskMoveResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskMoveResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskMoveResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskMoveResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskMoveResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskMoveResponseValidationError) ErrorName() string {
	return "ProjectTaskMoveResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskMoveResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskMoveResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskMoveResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskMoveResponseValidationError{}

// Validate checks the field values on ProjectTaskDetailRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskDetailRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskDetailRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskDetailRequestMultiError, or nil if none found.
func (m *ProjectTaskDetailRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskDetailRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	if len(errors) > 0 {
		return ProjectTaskDetailRequestMultiError(errors)
	}

	return nil
}

// ProjectTaskDetailRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskDetailRequest.ValidateAll() if the designated
// constraints aren't met.
type ProjectTaskDetailRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskDetailRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskDetailRequestMultiError) AllErrors() []error { return m }

// ProjectTaskDetailRequestValidationError is the validation error returned by
// ProjectTaskDetailRequest.Validate if the designated constraints aren't met.
type ProjectTaskDetailRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskDetailRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskDetailRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskDetailRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskDetailRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskDetailRequestValidationError) ErrorName() string {
	return "ProjectTaskDetailRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskDetailRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskDetailRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskDetailRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskDetailRequestValidationError{}

// Validate checks the field values on ProjectTaskDetailResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskDetailResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskDetailResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskDetailResponseMultiError, or nil if none found.
func (m *ProjectTaskDetailResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskDetailResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Description

	// no validation rules for CreatedAt

	if all {
		switch v := interface{}(m.GetAssigner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProjectTaskDetailResponseValidationError{
					field:  "Assigner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProjectTaskDetailResponseValidationError{
					field:  "Assigner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAssigner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectTaskDetailResponseValidationError{
				field:  "Assigner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetExecutor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProjectTaskDetailResponseValidationError{
					field:  "Executor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProjectTaskDetailResponseValidationError{
					field:  "Executor",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExecutor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectTaskDetailResponseValidationError{
				field:  "Executor",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ProjectTaskDetailResponseMultiError(errors)
	}

	return nil
}

// ProjectTaskDetailResponseMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskDetailResponse.ValidateAll() if the
// designated constraints aren't met.
type ProjectTaskDetailResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskDetailResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskDetailResponseMultiError) AllErrors() []error { return m }

// ProjectTaskDetailResponseValidationError is the validation error returned by
// ProjectTaskDetailResponse.Validate if the designated constraints aren't met.
type ProjectTaskDetailResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskDetailResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskDetailResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskDetailResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskDetailResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskDetailResponseValidationError) ErrorName() string {
	return "ProjectTaskDetailResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskDetailResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskDetailResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskDetailResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskDetailResponseValidationError{}

// Validate checks the field values on ProjectTaskTypeNameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskTypeNameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskTypeNameRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskTypeNameRequestMultiError, or nil if none found.
func (m *ProjectTaskTypeNameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskTypeNameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	// no validation rules for Name

	if len(errors) > 0 {
		return ProjectTaskTypeNameRequestMultiError(errors)
	}

	return nil
}

// ProjectTaskTypeNameRequestMultiError is an error wrapping multiple
// validation errors returned by ProjectTaskTypeNameRequest.ValidateAll() if
// the designated constraints aren't met.
type ProjectTaskTypeNameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskTypeNameRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskTypeNameRequestMultiError) AllErrors() []error { return m }

// ProjectTaskTypeNameRequestValidationError is the validation error returned
// by ProjectTaskTypeNameRequest.Validate if the designated constraints aren't met.
type ProjectTaskTypeNameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskTypeNameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskTypeNameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskTypeNameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskTypeNameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskTypeNameRequestValidationError) ErrorName() string {
	return "ProjectTaskTypeNameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskTypeNameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskTypeNameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskTypeNameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskTypeNameRequestValidationError{}

// Validate checks the field values on ProjectTaskTypeNameResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskTypeNameResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskTypeNameResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskTypeNameResponseMultiError, or nil if none found.
func (m *ProjectTaskTypeNameResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskTypeNameResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ProjectTaskTypeNameResponseMultiError(errors)
	}

	return nil
}

// ProjectTaskTypeNameResponseMultiError is an error wrapping multiple
// validation errors returned by ProjectTaskTypeNameResponse.ValidateAll() if
// the designated constraints aren't met.
type ProjectTaskTypeNameResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskTypeNameResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskTypeNameResponseMultiError) AllErrors() []error { return m }

// ProjectTaskTypeNameResponseValidationError is the validation error returned
// by ProjectTaskTypeNameResponse.Validate if the designated constraints
// aren't met.
type ProjectTaskTypeNameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskTypeNameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskTypeNameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskTypeNameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskTypeNameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskTypeNameResponseValidationError) ErrorName() string {
	return "ProjectTaskTypeNameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskTypeNameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskTypeNameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskTypeNameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskTypeNameResponseValidationError{}

// Validate checks the field values on ProjectCoexecutorsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectCoexecutorsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectCoexecutorsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectCoexecutorsRequestMultiError, or nil if none found.
func (m *ProjectCoexecutorsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectCoexecutorsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	if len(errors) > 0 {
		return ProjectCoexecutorsRequestMultiError(errors)
	}

	return nil
}

// ProjectCoexecutorsRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectCoexecutorsRequest.ValidateAll() if the
// designated constraints aren't met.
type ProjectCoexecutorsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectCoexecutorsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectCoexecutorsRequestMultiError) AllErrors() []error { return m }

// ProjectCoexecutorsRequestValidationError is the validation error returned by
// ProjectCoexecutorsRequest.Validate if the designated constraints aren't met.
type ProjectCoexecutorsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectCoexecutorsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectCoexecutorsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectCoexecutorsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectCoexecutorsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectCoexecutorsRequestValidationError) ErrorName() string {
	return "ProjectCoexecutorsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectCoexecutorsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectCoexecutorsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectCoexecutorsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectCoexecutorsRequestValidationError{}

// Validate checks the field values on ProjectCoexecutorsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectCoexecutorsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectCoexecutorsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectCoexecutorsResponseMultiError, or nil if none found.
func (m *ProjectCoexecutorsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectCoexecutorsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectCoexecutorsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectCoexecutorsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectCoexecutorsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProjectCoexecutorsResponseMultiError(errors)
	}

	return nil
}

// ProjectCoexecutorsResponseMultiError is an error wrapping multiple
// validation errors returned by ProjectCoexecutorsResponse.ValidateAll() if
// the designated constraints aren't met.
type ProjectCoexecutorsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectCoexecutorsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectCoexecutorsResponseMultiError) AllErrors() []error { return m }

// ProjectCoexecutorsResponseValidationError is the validation error returned
// by ProjectCoexecutorsResponse.Validate if the designated constraints aren't met.
type ProjectCoexecutorsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectCoexecutorsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectCoexecutorsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectCoexecutorsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectCoexecutorsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectCoexecutorsResponseValidationError) ErrorName() string {
	return "ProjectCoexecutorsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectCoexecutorsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectCoexecutorsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectCoexecutorsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectCoexecutorsResponseValidationError{}

// Validate checks the field values on ProjectWatchersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectWatchersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectWatchersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectWatchersRequestMultiError, or nil if none found.
func (m *ProjectWatchersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectWatchersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskId

	if len(errors) > 0 {
		return ProjectWatchersRequestMultiError(errors)
	}

	return nil
}

// ProjectWatchersRequestMultiError is an error wrapping multiple validation
// errors returned by ProjectWatchersRequest.ValidateAll() if the designated
// constraints aren't met.
type ProjectWatchersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectWatchersRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectWatchersRequestMultiError) AllErrors() []error { return m }

// ProjectWatchersRequestValidationError is the validation error returned by
// ProjectWatchersRequest.Validate if the designated constraints aren't met.
type ProjectWatchersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectWatchersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectWatchersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectWatchersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectWatchersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectWatchersRequestValidationError) ErrorName() string {
	return "ProjectWatchersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectWatchersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectWatchersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectWatchersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectWatchersRequestValidationError{}

// Validate checks the field values on ProjectWatchersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectWatchersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectWatchersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectWatchersResponseMultiError, or nil if none found.
func (m *ProjectWatchersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectWatchersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectWatchersResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectWatchersResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectWatchersResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProjectWatchersResponseMultiError(errors)
	}

	return nil
}

// ProjectWatchersResponseMultiError is an error wrapping multiple validation
// errors returned by ProjectWatchersResponse.ValidateAll() if the designated
// constraints aren't met.
type ProjectWatchersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectWatchersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectWatchersResponseMultiError) AllErrors() []error { return m }

// ProjectWatchersResponseValidationError is the validation error returned by
// ProjectWatchersResponse.Validate if the designated constraints aren't met.
type ProjectWatchersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectWatchersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectWatchersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectWatchersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectWatchersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectWatchersResponseValidationError) ErrorName() string {
	return "ProjectWatchersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectWatchersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectWatchersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectWatchersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectWatchersResponseValidationError{}

// Validate checks the field values on ProjectTaskResponse_Tasks with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskResponse_Tasks) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskResponse_Tasks with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectTaskResponse_TasksMultiError, or nil if none found.
func (m *ProjectTaskResponse_Tasks) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskResponse_Tasks) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	if len(errors) > 0 {
		return ProjectTaskResponse_TasksMultiError(errors)
	}

	return nil
}

// ProjectTaskResponse_TasksMultiError is an error wrapping multiple validation
// errors returned by ProjectTaskResponse_Tasks.ValidateAll() if the
// designated constraints aren't met.
type ProjectTaskResponse_TasksMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskResponse_TasksMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskResponse_TasksMultiError) AllErrors() []error { return m }

// ProjectTaskResponse_TasksValidationError is the validation error returned by
// ProjectTaskResponse_Tasks.Validate if the designated constraints aren't met.
type ProjectTaskResponse_TasksValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskResponse_TasksValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskResponse_TasksValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskResponse_TasksValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskResponse_TasksValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskResponse_TasksValidationError) ErrorName() string {
	return "ProjectTaskResponse_TasksValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskResponse_TasksValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskResponse_Tasks.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskResponse_TasksValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskResponse_TasksValidationError{}

// Validate checks the field values on ProjectTaskResponse_Categories with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectTaskResponse_Categories) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskResponse_Categories with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ProjectTaskResponse_CategoriesMultiError, or nil if none found.
func (m *ProjectTaskResponse_Categories) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskResponse_Categories) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	for idx, item := range m.GetTasks() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectTaskResponse_CategoriesValidationError{
						field:  fmt.Sprintf("Tasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectTaskResponse_CategoriesValidationError{
						field:  fmt.Sprintf("Tasks[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectTaskResponse_CategoriesValidationError{
					field:  fmt.Sprintf("Tasks[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProjectTaskResponse_CategoriesMultiError(errors)
	}

	return nil
}

// ProjectTaskResponse_CategoriesMultiError is an error wrapping multiple
// validation errors returned by ProjectTaskResponse_Categories.ValidateAll()
// if the designated constraints aren't met.
type ProjectTaskResponse_CategoriesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskResponse_CategoriesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskResponse_CategoriesMultiError) AllErrors() []error { return m }

// ProjectTaskResponse_CategoriesValidationError is the validation error
// returned by ProjectTaskResponse_Categories.Validate if the designated
// constraints aren't met.
type ProjectTaskResponse_CategoriesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskResponse_CategoriesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskResponse_CategoriesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskResponse_CategoriesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskResponse_CategoriesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskResponse_CategoriesValidationError) ErrorName() string {
	return "ProjectTaskResponse_CategoriesValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskResponse_CategoriesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskResponse_Categories.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskResponse_CategoriesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskResponse_CategoriesValidationError{}

// Validate checks the field values on ProjectTaskDetailResponse_Member with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ProjectTaskDetailResponse_Member) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectTaskDetailResponse_Member with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ProjectTaskDetailResponse_MemberMultiError, or nil if none found.
func (m *ProjectTaskDetailResponse_Member) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectTaskDetailResponse_Member) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	if len(errors) > 0 {
		return ProjectTaskDetailResponse_MemberMultiError(errors)
	}

	return nil
}

// ProjectTaskDetailResponse_MemberMultiError is an error wrapping multiple
// validation errors returned by
// ProjectTaskDetailResponse_Member.ValidateAll() if the designated
// constraints aren't met.
type ProjectTaskDetailResponse_MemberMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectTaskDetailResponse_MemberMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectTaskDetailResponse_MemberMultiError) AllErrors() []error { return m }

// ProjectTaskDetailResponse_MemberValidationError is the validation error
// returned by ProjectTaskDetailResponse_Member.Validate if the designated
// constraints aren't met.
type ProjectTaskDetailResponse_MemberValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectTaskDetailResponse_MemberValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectTaskDetailResponse_MemberValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectTaskDetailResponse_MemberValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectTaskDetailResponse_MemberValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectTaskDetailResponse_MemberValidationError) ErrorName() string {
	return "ProjectTaskDetailResponse_MemberValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectTaskDetailResponse_MemberValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectTaskDetailResponse_Member.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectTaskDetailResponse_MemberValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectTaskDetailResponse_MemberValidationError{}

// Validate checks the field values on ProjectCoexecutorsResponse_Item with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectCoexecutorsResponse_Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectCoexecutorsResponse_Item with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ProjectCoexecutorsResponse_ItemMultiError, or nil if none found.
func (m *ProjectCoexecutorsResponse_Item) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectCoexecutorsResponse_Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	if len(errors) > 0 {
		return ProjectCoexecutorsResponse_ItemMultiError(errors)
	}

	return nil
}

// ProjectCoexecutorsResponse_ItemMultiError is an error wrapping multiple
// validation errors returned by ProjectCoexecutorsResponse_Item.ValidateAll()
// if the designated constraints aren't met.
type ProjectCoexecutorsResponse_ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectCoexecutorsResponse_ItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectCoexecutorsResponse_ItemMultiError) AllErrors() []error { return m }

// ProjectCoexecutorsResponse_ItemValidationError is the validation error
// returned by ProjectCoexecutorsResponse_Item.Validate if the designated
// constraints aren't met.
type ProjectCoexecutorsResponse_ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectCoexecutorsResponse_ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectCoexecutorsResponse_ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectCoexecutorsResponse_ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectCoexecutorsResponse_ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectCoexecutorsResponse_ItemValidationError) ErrorName() string {
	return "ProjectCoexecutorsResponse_ItemValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectCoexecutorsResponse_ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectCoexecutorsResponse_Item.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectCoexecutorsResponse_ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectCoexecutorsResponse_ItemValidationError{}

// Validate checks the field values on ProjectWatchersResponse_Item with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectWatchersResponse_Item) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectWatchersResponse_Item with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectWatchersResponse_ItemMultiError, or nil if none found.
func (m *ProjectWatchersResponse_Item) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectWatchersResponse_Item) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	if len(errors) > 0 {
		return ProjectWatchersResponse_ItemMultiError(errors)
	}

	return nil
}

// ProjectWatchersResponse_ItemMultiError is an error wrapping multiple
// validation errors returned by ProjectWatchersResponse_Item.ValidateAll() if
// the designated constraints aren't met.
type ProjectWatchersResponse_ItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectWatchersResponse_ItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectWatchersResponse_ItemMultiError) AllErrors() []error { return m }

// ProjectWatchersResponse_ItemValidationError is the validation error returned
// by ProjectWatchersResponse_Item.Validate if the designated constraints
// aren't met.
type ProjectWatchersResponse_ItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectWatchersResponse_ItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectWatchersResponse_ItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectWatchersResponse_ItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectWatchersResponse_ItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectWatchersResponse_ItemValidationError) ErrorName() string {
	return "ProjectWatchersResponse_ItemValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectWatchersResponse_ItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectWatchersResponse_Item.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectWatchersResponse_ItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectWatchersResponse_ItemValidationError{}
