// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"voo.su/internal/cli"
	"voo.su/internal/cli/handler/cron"
	"voo.su/internal/cli/handler/queue"
	"voo.su/internal/config"
	"voo.su/internal/delivery/grpc"
	handler3 "voo.su/internal/delivery/grpc/handler"
	"voo.su/internal/delivery/grpc/middleware"
	"voo.su/internal/delivery/http"
	"voo.su/internal/delivery/http/handler"
	"voo.su/internal/delivery/http/handler/bot"
	"voo.su/internal/delivery/http/handler/v1"
	"voo.su/internal/delivery/http/router"
	"voo.su/internal/delivery/ws"
	"voo.su/internal/delivery/ws/consume"
	chat2 "voo.su/internal/delivery/ws/consume/chat"
	"voo.su/internal/delivery/ws/event"
	"voo.su/internal/delivery/ws/event/chat"
	handler2 "voo.su/internal/delivery/ws/handler"
	"voo.su/internal/delivery/ws/process"
	router2 "voo.su/internal/delivery/ws/router"
	"voo.su/internal/domain/logic"
	"voo.su/internal/infrastructure"
	repository3 "voo.su/internal/infrastructure/clickhouse/repository"
	repository2 "voo.su/internal/infrastructure/postgres/repository"
	"voo.su/internal/infrastructure/redis/repository"
	"voo.su/internal/provider"
	"voo.su/internal/usecase"
)

// Injectors from wire.go:

func NewHttpInjector(conf *config.Config) *http.AppProvider {
	email := provider.NewEmailClient(conf)
	client := provider.NewRedisClient(conf)
	smsCacheRepository := repository.NewSmsCacheRepository(client)
	db := provider.NewPostgresqlClient(conf)
	contactRemarkCacheRepository := repository.NewContactRemarkCacheRepository(client)
	relationCacheRepository := repository.NewRelationCacheRepository(client)
	contactRepository := repository2.NewContactRepository(db, contactRemarkCacheRepository, relationCacheRepository)
	groupChatMemberRepository := repository2.NewGroupMemberRepository(db, relationCacheRepository)
	groupChatRepository := repository2.NewGroupChatRepository(db)
	userRepository := repository2.NewUserRepository(db)
	conn := provider.NewClickHouseClient(conf)
	authCodeRepository := repository3.NewAuthCodeRepository(conn)
	authUseCase := usecase.NewAuthUseCase(conf, email, smsCacheRepository, contactRepository, groupChatMemberRepository, groupChatRepository, userRepository, authCodeRepository)
	jwtTokenCacheRepository := repository.NewJwtTokenCacheRepository(client)
	source := infrastructure.NewSource(db, client)
	httpClient := provider.NewHttpClient()
	requestClient := provider.NewRequestClient(httpClient)
	ipAddressUseCase := usecase.NewIpAddressUseCase(source, conf, requestClient)
	chatRepository := repository2.NewChatRepository(db)
	chatUseCase := usecase.NewChatUseCase(source, chatRepository, groupChatMemberRepository)
	botRepository := repository2.NewBotRepository(db)
	iMinio := provider.NewMinioClient(conf)
	botUseCase := usecase.NewBotUseCase(source, conf, botRepository, userRepository, iMinio)
	userSessionRepository := repository2.NewUserSessionRepository(db)
	pushTokenRepository := repository2.NewPushTokenRepository(db)
	userUseCase := usecase.NewUserUseCase(source, userRepository, userSessionRepository, pushTokenRepository)
	sequenceCacheRepository := repository.NewSequenceCacheRepository(client)
	sequenceRepository := repository2.NewSequenceRepository(db, sequenceCacheRepository)
	messageForwardLogic := logic.NewMessageForwardLogic(db, sequenceRepository)
	fileSplitRepository := repository2.NewFileSplitRepository(db)
	voteCacheRepository := repository.NewVoteCacheRepository(client)
	messageVoteRepository := repository2.NewMessageVoteRepository(db, voteCacheRepository)
	messageRepository := repository2.NewMessageRepository(db)
	unreadCacheRepository := repository.NewUnreadCacheRepository(client)
	messageCacheRepository := repository.NewMessageCacheRepository(client)
	serverCacheRepository := repository.NewServerCacheRepository(client)
	clientCacheRepository := repository.NewClientCacheRepository(conf, client, serverCacheRepository)
	iNatsClient := provider.NewNatsClient(conf)
	messageUseCase := &usecase.MessageUseCase{
		Source:              source,
		Conf:                conf,
		MessageForwardLogic: messageForwardLogic,
		Minio:               iMinio,
		GroupChatMemberRepo: groupChatMemberRepository,
		FileSplitRepo:       fileSplitRepository,
		MessageVoteRepo:     messageVoteRepository,
		Sequence:            sequenceRepository,
		MessageRepo:         messageRepository,
		BotRepo:             botRepository,
		UnreadCache:         unreadCacheRepository,
		MessageCache:        messageCacheRepository,
		ServerCache:         serverCacheRepository,
		ClientCache:         clientCacheRepository,
		DialogVoteCache:     voteCacheRepository,
		Nats:                iNatsClient,
	}
	auth := &v1.Auth{
		Conf:              conf,
		AuthUseCase:       authUseCase,
		JwtTokenCacheRepo: jwtTokenCacheRepository,
		IpAddressUseCase:  ipAddressUseCase,
		ChatUseCase:       chatUseCase,
		BotUseCase:        botUseCase,
		UserUseCase:       userUseCase,
		MessageUseCase:    messageUseCase,
	}
	account := &v1.Account{
		UserUseCase: userUseCase,
	}
	contactUseCase := usecase.NewContactUseCase(source, contactRepository)
	contact := &v1.Contact{
		ContactUseCase: contactUseCase,
		ChatUseCase:    chatUseCase,
		UserUseCase:    userUseCase,
		MessageUseCase: messageUseCase,
	}
	contactRequestUseCase := usecase.NewContactRequestUseCase(source)
	contactRequest := &v1.ContactRequest{
		ContactRequestUseCase: contactRequestUseCase,
		ContactUseCase:        contactUseCase,
		MessageUseCase:        messageUseCase,
	}
	groupChatUseCase := usecase.NewGroupChatUseCase(source, groupChatRepository, groupChatMemberRepository, sequenceRepository, relationCacheRepository)
	redisLockCacheRepository := repository.NewRedisLockCacheRepository(client)
	chat := &v1.Chat{
		ChatUseCase:            chatUseCase,
		ContactUseCase:         contactUseCase,
		GroupChatUseCase:       groupChatUseCase,
		AuthUseCase:            authUseCase,
		UserUseCase:            userUseCase,
		RedisLockRepo:          redisLockCacheRepository,
		ClientCacheRepo:        clientCacheRepository,
		MessageCacheRepo:       messageCacheRepository,
		UnreadCacheRepo:        unreadCacheRepository,
		ContactRemarkCacheRepo: contactRemarkCacheRepository,
	}
	groupChatMemberUseCase := usecase.NewGroupMemberUseCase(source, groupChatMemberRepository)
	message := &v1.Message{
		Conf:                   conf,
		ChatUseCase:            chatUseCase,
		AuthUseCase:            authUseCase,
		MessageUseCase:         messageUseCase,
		Minio:                  iMinio,
		GroupChatMemberUseCase: groupChatMemberUseCase,
	}
	publish := &v1.Publish{
		AuthUseCase:    authUseCase,
		MessageUseCase: messageUseCase,
	}
	fileSplitUseCase := usecase.NewFileSplitUseCase(source, conf, fileSplitRepository, iMinio)
	upload := &v1.Upload{
		Conf:             conf,
		Minio:            iMinio,
		FileSplitUseCase: fileSplitUseCase,
	}
	groupChat := &v1.GroupChat{
		GroupChatUseCase:       groupChatUseCase,
		GroupChatMemberUseCase: groupChatMemberUseCase,
		ChatUseCase:            chatUseCase,
		ContactUseCase:         contactUseCase,
		MessageUseCase:         messageUseCase,
		UserUseCase:            userUseCase,
		RedisLockCacheRepo:     redisLockCacheRepository,
	}
	groupChatRequestCacheRepository := repository.NewGroupChatRequestCacheRepository(client)
	groupChatRequestRepository := repository2.NewGroupChatApplyRepository(db)
	groupChatRequestUseCase := usecase.NewGroupRequestUseCase(source, groupChatRequestRepository)
	groupChatRequest := &v1.GroupChatRequest{
		GroupRequestCacheRepo:   groupChatRequestCacheRepository,
		GroupChatRequestUseCase: groupChatRequestUseCase,
		GroupChatMemberUseCase:  groupChatMemberUseCase,
		GroupChatUseCase:        groupChatUseCase,
		Redis:                   client,
	}
	stickerRepository := repository2.NewStickerRepository(db)
	stickerUseCase := usecase.NewStickerUseCase(source, stickerRepository, iMinio)
	sticker := &v1.Sticker{
		Conf:               conf,
		StickerUseCase:     stickerUseCase,
		Minio:              iMinio,
		RedisLockCacheRepo: redisLockCacheRepository,
	}
	contactFolderRepository := repository2.NewContactFolderRepository(db)
	contactFolderUseCase := usecase.NewContactFolderUseCase(source, contactRepository, contactFolderRepository)
	contactFolder := &v1.ContactFolder{
		ContactFolderUseCase: contactFolderUseCase,
	}
	groupChatAdsRepository := repository2.NewGroupChatAdsRepository(db)
	groupChatAdsUseCase := usecase.NewGroupChatAdsUseCase(source, groupChatAdsRepository)
	groupChatAds := &v1.GroupChatAds{
		GroupMemberUseCase:  groupChatMemberUseCase,
		GroupChatAdsUseCase: groupChatAdsUseCase,
		MessageUseCase:      messageUseCase,
	}
	search := &v1.Search{
		UserUseCase:      userUseCase,
		GroupChatUseCase: groupChatUseCase,
	}
	v1Bot := &v1.Bot{
		BotUseCase:     botUseCase,
		MessageUseCase: messageUseCase,
	}
	projectRepository := repository2.NewProjectRepository(db)
	projectMemberRepository := repository2.NewProjectMemberRepository(db)
	projectTaskTypeRepository := repository2.NewProjectTaskTypeRepository(db)
	projectTaskRepository := repository2.NewProjectTaskRepository(db)
	projectTaskCommentRepository := repository2.NewProjectTaskCommentRepository(db)
	projectTaskCoexecutorRepository := repository2.NewProjectTaskCoexecutorRepository(db)
	projectTaskWatcherRepository := repository2.NewProjectTaskWatcherRepository(db)
	projectUseCase := usecase.NewProjectUseCase(source, projectRepository, projectMemberRepository, projectTaskTypeRepository, projectTaskRepository, projectTaskCommentRepository, userRepository, relationCacheRepository, projectTaskCoexecutorRepository, projectTaskWatcherRepository)
	project := &v1.Project{
		ProjectUseCase:     projectUseCase,
		RedisLockCacheRepo: redisLockCacheRepository,
	}
	projectTask := &v1.ProjectTask{
		ProjectUseCase: projectUseCase,
	}
	projectTaskComment := &v1.ProjectTaskComment{
		ProjectUseCase: projectUseCase,
	}
	v1Handler := &v1.Handler{
		Auth:               auth,
		Account:            account,
		Contact:            contact,
		ContactRequest:     contactRequest,
		Chat:               chat,
		Message:            message,
		MessagePublish:     publish,
		Upload:             upload,
		GroupChat:          groupChat,
		GroupChatRequest:   groupChatRequest,
		Sticker:            sticker,
		ContactFolder:      contactFolder,
		GroupChatAds:       groupChatAds,
		Search:             search,
		Bot:                v1Bot,
		Project:            project,
		ProjectTask:        projectTask,
		ProjectTaskComment: projectTaskComment,
	}
	botMessage := &bot.Message{
		MessageUseCase: messageUseCase,
		BotUseCase:     botUseCase,
	}
	botHandler := &bot.Handler{
		Message: botMessage,
	}
	handlerHandler := &handler.Handler{
		V1:  v1Handler,
		Bot: botHandler,
	}
	engine := router.NewRouter(conf, handlerHandler, jwtTokenCacheRepository)
	appProvider := &http.AppProvider{
		Conf:   conf,
		Engine: engine,
	}
	return appProvider
}

func NewWsInjector(conf *config.Config) *ws.AppProvider {
	client := provider.NewRedisClient(conf)
	serverCacheRepository := repository.NewServerCacheRepository(client)
	clientCacheRepository := repository.NewClientCacheRepository(conf, client, serverCacheRepository)
	roomCacheRepository := repository.NewRoomCacheRepository(client)
	db := provider.NewPostgresqlClient(conf)
	relationCacheRepository := repository.NewRelationCacheRepository(client)
	groupChatMemberRepository := repository2.NewGroupMemberRepository(db, relationCacheRepository)
	source := infrastructure.NewSource(db, client)
	groupChatMemberUseCase := usecase.NewGroupMemberUseCase(source, groupChatMemberRepository)
	chatHandler := chat.NewHandler(client, groupChatMemberUseCase)
	chatEvent := &event.ChatEvent{
		Redis:                  client,
		Conf:                   conf,
		RoomCache:              roomCacheRepository,
		GroupChatMemberRepo:    groupChatMemberRepository,
		GroupChatMemberUseCase: groupChatMemberUseCase,
		Handler:                chatHandler,
	}
	chatChannel := &handler2.ChatChannel{
		ClientCacheRepo: clientCacheRepository,
		Event:           chatEvent,
	}
	handlerHandler := &handler2.Handler{
		Chat: chatChannel,
		Conf: conf,
	}
	jwtTokenCacheRepository := repository.NewJwtTokenCacheRepository(client)
	engine := router2.NewRouter(conf, handlerHandler, jwtTokenCacheRepository)
	healthSubscribe := process.NewHealthSubscribe(conf, serverCacheRepository)
	chatRepository := repository2.NewChatRepository(db)
	chatUseCase := usecase.NewChatUseCase(source, chatRepository, groupChatMemberRepository)
	sequenceCacheRepository := repository.NewSequenceCacheRepository(client)
	sequenceRepository := repository2.NewSequenceRepository(db, sequenceCacheRepository)
	messageForwardLogic := logic.NewMessageForwardLogic(db, sequenceRepository)
	iMinio := provider.NewMinioClient(conf)
	fileSplitRepository := repository2.NewFileSplitRepository(db)
	voteCacheRepository := repository.NewVoteCacheRepository(client)
	messageVoteRepository := repository2.NewMessageVoteRepository(db, voteCacheRepository)
	messageRepository := repository2.NewMessageRepository(db)
	botRepository := repository2.NewBotRepository(db)
	unreadCacheRepository := repository.NewUnreadCacheRepository(client)
	messageCacheRepository := repository.NewMessageCacheRepository(client)
	iNatsClient := provider.NewNatsClient(conf)
	messageUseCase := &usecase.MessageUseCase{
		Source:              source,
		Conf:                conf,
		MessageForwardLogic: messageForwardLogic,
		Minio:               iMinio,
		GroupChatMemberRepo: groupChatMemberRepository,
		FileSplitRepo:       fileSplitRepository,
		MessageVoteRepo:     messageVoteRepository,
		Sequence:            sequenceRepository,
		MessageRepo:         messageRepository,
		BotRepo:             botRepository,
		UnreadCache:         unreadCacheRepository,
		MessageCache:        messageCacheRepository,
		ServerCache:         serverCacheRepository,
		ClientCache:         clientCacheRepository,
		DialogVoteCache:     voteCacheRepository,
		Nats:                iNatsClient,
	}
	contactRemarkCacheRepository := repository.NewContactRemarkCacheRepository(client)
	contactRepository := repository2.NewContactRepository(db, contactRemarkCacheRepository, relationCacheRepository)
	contactUseCase := usecase.NewContactUseCase(source, contactRepository)
	handler3 := &chat2.Handler{
		Source:         source,
		Conf:           conf,
		ClientCache:    clientCacheRepository,
		RoomCache:      roomCacheRepository,
		ChatUseCase:    chatUseCase,
		MessageUseCase: messageUseCase,
		ContactUseCase: contactUseCase,
	}
	chatSubscribe := consume.NewChatSubscribe(handler3)
	messageSubscribe := process.NewMessageSubscribe(conf, client, chatSubscribe)
	subServers := &process.SubServers{
		HealthSubscribe:  healthSubscribe,
		MessageSubscribe: messageSubscribe,
	}
	server := process.NewServer(subServers)
	email := provider.NewEmailClient(conf)
	providers := &provider.Providers{
		EmailClient: email,
	}
	appProvider := &ws.AppProvider{
		Conf:      conf,
		Engine:    engine,
		Coroutine: server,
		Handler:   handlerHandler,
		Providers: providers,
	}
	return appProvider
}

func NewGrpcInjector(conf *config.Config) *grpc.AppProvider {
	tokenMiddleware := middleware.NewTokenMiddleware(conf)
	grpcMethodService := middleware.NewGrpMethodsService()
	email := provider.NewEmailClient(conf)
	client := provider.NewRedisClient(conf)
	smsCacheRepository := repository.NewSmsCacheRepository(client)
	db := provider.NewPostgresqlClient(conf)
	contactRemarkCacheRepository := repository.NewContactRemarkCacheRepository(client)
	relationCacheRepository := repository.NewRelationCacheRepository(client)
	contactRepository := repository2.NewContactRepository(db, contactRemarkCacheRepository, relationCacheRepository)
	groupChatMemberRepository := repository2.NewGroupMemberRepository(db, relationCacheRepository)
	groupChatRepository := repository2.NewGroupChatRepository(db)
	userRepository := repository2.NewUserRepository(db)
	conn := provider.NewClickHouseClient(conf)
	authCodeRepository := repository3.NewAuthCodeRepository(conn)
	authUseCase := usecase.NewAuthUseCase(conf, email, smsCacheRepository, contactRepository, groupChatMemberRepository, groupChatRepository, userRepository, authCodeRepository)
	jwtTokenCacheRepository := repository.NewJwtTokenCacheRepository(client)
	source := infrastructure.NewSource(db, client)
	httpClient := provider.NewHttpClient()
	requestClient := provider.NewRequestClient(httpClient)
	ipAddressUseCase := usecase.NewIpAddressUseCase(source, conf, requestClient)
	chatRepository := repository2.NewChatRepository(db)
	chatUseCase := usecase.NewChatUseCase(source, chatRepository, groupChatMemberRepository)
	botRepository := repository2.NewBotRepository(db)
	userSessionRepository := repository2.NewUserSessionRepository(db)
	authHandler := handler3.NewAuthHandler(conf, tokenMiddleware, authUseCase, jwtTokenCacheRepository, ipAddressUseCase, chatUseCase, botRepository, userSessionRepository)
	contactUseCase := usecase.NewContactUseCase(source, contactRepository)
	messageCacheRepository := repository.NewMessageCacheRepository(client)
	unreadCacheRepository := repository.NewUnreadCacheRepository(client)
	chatHandler := handler3.NewChatHandler(conf, contactUseCase, chatUseCase, messageCacheRepository, unreadCacheRepository)
	contactHandler := handler3.NewContactHandler(conf, tokenMiddleware, contactUseCase)
	appProvider := &grpc.AppProvider{
		Conf:            conf,
		TokenMiddleware: tokenMiddleware,
		RoutesServices:  grpcMethodService,
		AuthHandler:     authHandler,
		ChatHandler:     chatHandler,
		ContactHandler:  contactHandler,
	}
	return appProvider
}

func NewCronInjector(conf *config.Config) *cli.CronProvider {
	client := provider.NewRedisClient(conf)
	serverCacheRepository := repository.NewServerCacheRepository(client)
	clearWsCache := cron.NewClearWsCache(serverCacheRepository)
	db := provider.NewPostgresqlClient(conf)
	iMinio := provider.NewMinioClient(conf)
	clearTmpFile := cron.NewClearTmpFile(conf, db, iMinio)
	clearExpireServer := cron.NewClearExpireServer(serverCacheRepository)
	crontab := &cli.Crontab{
		ClearWsCache:      clearWsCache,
		ClearTmpFile:      clearTmpFile,
		ClearExpireServer: clearExpireServer,
	}
	cronProvider := &cli.CronProvider{
		Conf:    conf,
		Crontab: crontab,
	}
	return cronProvider
}

func NewQueueInjector(conf *config.Config) *cli.QueueProvider {
	db := provider.NewPostgresqlClient(conf)
	client := provider.NewRedisClient(conf)
	emailHandle := queue.EmailHandle{
		Redis: client,
	}
	iNatsClient := provider.NewNatsClient(conf)
	pushHandle := queue.PushHandle{
		Conf: conf,
		Nats: iNatsClient,
	}
	queueJobs := &cli.QueueJobs{
		EmailHandle: emailHandle,
		PushHandle:  pushHandle,
	}
	queueProvider := &cli.QueueProvider{
		Conf: conf,
		DB:   db,
		Jobs: queueJobs,
	}
	return queueProvider
}

func NewMigrateInjector(conf *config.Config) *cli.MigrateProvider {
	db := provider.NewPostgresqlClient(conf)
	migrateProvider := &cli.MigrateProvider{
		Conf: conf,
		DB:   db,
	}
	return migrateProvider
}

func NewGenerateInjector(conf *config.Config) *cli.GenerateProvider {
	generateProvider := &cli.GenerateProvider{}
	return generateProvider
}

// wire.go:

var providerSet = wire.NewSet(provider.NewPostgresqlClient, provider.NewClickHouseClient, provider.NewRedisClient, provider.NewHttpClient, provider.NewEmailClient, provider.NewMinioClient, provider.NewRequestClient, provider.NewNatsClient, wire.Struct(new(provider.Providers), "*"), logic.ProviderSet, usecase.ProviderSet, infrastructure.ProviderSet)
