postgresql:
  host: xxx.xxx.xxx.xxx
  port: 5432
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

clickhouse:
  host: xxx.xxx.xxx.xxx
  port: 9000
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

redis:
  host: xxx.xxx.xxx.xxx:6379
  auth:
  database: 0
