app:
  env: dev
  jwt:
    secret: voo_su
    expires_time: 2678400
    buffer_time: 2678400
  cors:
    origin: "*"
    headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
    methods: "OPTIONS,GET,POST,PUT,DELETE"
    credentials: false
    max_age: 600

server:
  http:
    host: 127.0.0.1
    port: 8000
  ws:
    host: 127.0.0.1
    port: 8001
  tcp:
    host: 127.0.0.1
    port: 8002
  grpc:
    host: 127.0.0.1
    port: 50051
    protocol: tcp

postgres:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  database: voo_su

clickhouse:
  host: 127.0.0.1
  port: 9000
  username: clickhouse
  password: clickhouse
  database: voo_su

minio:
  host: 127.0.0.1
  ssl: false
  secret_id: minio_user
  secret_key: minio_password
  bucket: voo_su

redis:
  host: 127.0.0.1:6379
  auth:
  database: 0

nats:
  host: 127.0.0.1
  port: 4222

email:
  host: xxx.xxx.xxx.xxx
  port: 25
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  from: xxx@xxx.xxx
  name: xxxxxxxxxx
  report: xxx@xxx.xxx

push:
  web_push:
    private_key: xxxxxxxxxx
    public_key: xxxxxxxxxx
