app:
  env: dev
  log: ./runtime/log

server:
  http: xxxx
  ws: xxxx
  tcp: xxxx
  grpc_host: "127.0.0.1"
  grpc_port: xxxx
  grpc_protocol: "tcp"

jwt:
  secret: xxxxxxxxxxxxxxxxxx
  expires_time: xxxxxxx
  buffer_time: xxxxxxx

cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600

postgresql:
  host: xxx.xxx.xxx.xxx
  port: 5432
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

clickhouse:
  host: xxx.xxx.xxx.xxx
  port: 9000
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

redis:
  host: xxx.xxx.xxx.xxx:6379
  auth:
  database: 0

minio:
  endpoint: "xxx.xxx.xxx.xxx"
  ssl: false
  secret_id: ""
  secret_key: ""
  bucket_public: ""
  bucket_private: ""

email:
  host: xxx.xxx.xxx.xxx
  port: 25
  username:
  password:
  from: xxx@xxx.xxx
  name: Voo.su
  report: xxx@xxx.xxx
