app:
  env: dev
  default_lang: en
  jwt:
    secret: voo_su
    expires_time: 2678400
    buffer_time: 2678400
  cors:
    origin: "*"
    credentials: false
    max_age: 600

manager:
  ips:
    - 127.0.0.1
    - 192.168.1.2

server:
  http:
    host: 0.0.0.0
    port: 8000
  ws:
    host: 0.0.0.0
    port: 8001
  tcp:
    host: 0.0.0.0
    port: 8002
  grpc:
    host: 0.0.0.0
    port: 50051
    protocol: tcp

postgres:
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: voo_su

clickhouse:
  host: clickhouse
  port: 9000
  username: clickhouse
  password: clickhouse
  database: voo_su

minio:
  host: minio
  ssl: false
  secret_id: minio_user
  secret_key: minio_password
  bucket: voo_su

redis:
  host: redis:6379
  auth:
  database: 0

nats:
  host: nats
  port: 4222

email:
  host: xxx.xxx.xxx.xxx
  port: 25
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  from: xxx@xxx.xxx
  name: xxxxxxxxxx
  report: xxx@xxx.xxx

push:
  web_push:
    private_key: xxxxxxxxxx
    public_key: xxxxxxxxxx
  firebase:
    project_id: xxxxxxxxxx
    json_path: xxxxxxxxxx.json
