app:
  env: dev
  log: ./runtime/log

server:
  http: xxxx
  ws: xxxx
  tcp: xxxx
  grpc_host: "127.0.0.1"
  grpc_port: 50051
  grpc_protocol: "tcp"

postgresql:
  host: xxx.xxx.xxx.xxx
  port: 5432
  username: postgres
  password: postgres
  database: voo_su

redis:
  host: xxx.xxx.xxx.xxx:6379
  auth:
  database: 0

jwt:
  secret: xxxxxxxxxxxxxxxxxx
  expires_time: xxxxxxx
  buffer_time: xxxxxxx

cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600

file:
  default: local
  local:
    root: ./runtime/media
    domain:

email:
  host: xxx.xxx.xxx.xxx
  port: 25
  username:
  password:
  from: xxx@xxx.xxx
  name: Voo.su
  report: xxx@xxx.xxx
