app:
  env: dev
  jwt:
    secret: xxxxxxxxxxxxxxxxxx
    expires_time: xxxxxxx
    buffer_time: xxxxxxx
  cors:
    origin: "*"
    headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
    methods: "OPTIONS,GET,POST,PUT,DELETE"
    credentials: false
    max_age: 600

server:
  http:
    host: 127.0.0.1
    port: xxxx
  ws:
    host: 127.0.0.1
    port: xxxx
  tcp:
    host: 127.0.0.1
    port: xxxx
  grpc:
    host: 127.0.0.1
    port: xxxx
    protocol: tcp

postgres:
  host: xxx.xxx.xxx.xxx
  port: 5432
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

clickhouse:
  host: xxx.xxx.xxx.xxx
  port: 9000
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  database: xxxxxxxxxx

minio:
  host: xxx.xxx.xxx.xxx
  ssl: false
  secret_id: xxxxxxxxxx
  secret_key: xxxxxxxxxx
  bucket_public: xxxxxxxxxx
  bucket_private: xxxxxxxxxx

redis:
  host: xxx.xxx.xxx.xxx:6379
  auth:
  database: 0

email:
  host: xxx.xxx.xxx.xxx
  port: 25
  username: xxxxxxxxxx
  password: xxxxxxxxxx
  from: xxx@xxx.xxx
  name: xxxxxxxxxx
  report: xxx@xxx.xxx
