app:
  env: dev
  http: 8000
  ws: 8001
  tcp: 8002
  log: ./runtime/log

postgresql:
  host: postgres
  port: 5432
  username: postgres
  password: postgres
  database: voo_su

redis:
  host: redis:6379
  auth:
  database: 0

jwt:
  secret: g56KFY0q17rg6PoMGJF0MjsrTCjh2vBFHUphE4wJGtjeg9HxnTsnuWa157Oa
  expires_time: 2678400
  buffer_time: 2678400

cors:
  origin: "*"
  headers: "Content-Type,Cache-Control,User-Agent,Keep-Alive,DNT,AccessToken,Authorization"
  methods: "OPTIONS,GET,POST,PUT,DELETE"
  credentials: false
  max_age: 600

file:
  default: local
  local:
    root: ./runtime/media
    domain:

email:
  host: 127.0.0.1
  port: 25
  username:
  password:
  from: info@voo.su
  name: Voo.su
  report: info@magomedcoder.ru
